import { Item, Equipment } from '../Items/types';
import { ActiveEffect } from '../Effects/types';
import type { UpgradeableDieGear } from '../Combat/combat.encounter.types';

/**
 * A character's worn loadout. Exactly 5 worn pieces across 3 slot
 * kinds: 1 weapon, 1 armor, up to 3 interchangeable accessories. The three
 * accessory positions have no identity — an accessory occupies *an* accessory
 * position; declaration/array order is cosmetic. `accessories.length` is capped
 * at `SLOT_CAPACITY.accessory` (3).
 */
export interface EquipmentLoadout {
    weapon: Equipment | null;
    armor: Equipment | null;
    accessories: Equipment[];
}

/** A fresh, empty loadout (no piece worn in any slot). */
export const emptyLoadout = (): EquipmentLoadout => ({
    weapon: null,
    armor: null,
    accessories: [],
});

/**
 * The three core attributes from which all other character/enemy stats derive.
 *
 * @property heart - Emotion, willpower, charisma. Strong against `body`.
 * @property body  - Physical strength and constitution. Strong against `mind`.
 * @property mind  - Intelligence, reflexes, perception. Strong against `heart`.
 */
export interface BaseStats {
    heart: number;
    body: number;
    mind: number;
}

/**
 * The player character.
 *
 * @property id                     - Stable identifier. Auto-generated by
 *                                    `createCharacter` from `getRng()` when
 *                                    not supplied by the caller. Mirrors
 *                                    `Enemy.id` so `ActiveEffect.sourceId`
 *                                    can unambiguously point at the applier.
 * @property level                  - Determines stat scaling and abilities.
 * @property experience             - Total XP earned.
 * @property experienceToNextLevel  - XP threshold for the next level-up.
 * @property baseStats              - Heart/Body/Mind core attributes.
 * @property inventory              - Items the character is carrying.
 * @property equipment              - The worn `EquipmentLoadout`:
 *                                    1 weapon + 1 armor + ≤3 accessories.
 *                                    Equipment's only stat line is the armor
 *                                    relics' `maxHp`, folded onto `maxHealth`
 *                                    at equip-time.
 * @property effects                - Active status effects on the character.
 * @property knownCards            - IDs of cards the character has learned/unlocked.
 *                                    The combat catalogue is the learned set
 *                                    filtered by affordability (ADR-0002); there
 *                                    is no equipped-card loadout gate.
 * @property availableStatPoints    - Unspent stat points awaiting allocation
 *                                    Granted on level-up,
 *                                    spent via `allocateStatPoint`. Defaults
 *                                    to 0 for preset-built characters since
 *                                    presets ship pre-allocated.
 */
export interface Character {
    id: string;
    name: string;
    level: number;
    experience: number;
    experienceToNextLevel: number;
    health: number;
    maxHealth: number;
    baseStats: BaseStats;
    inventory: Item[];
    /**
     * Generic in-game currency counter. Spent / earned through the shop
     * reducers (`Items/shop.reducer.ts`).
     */
    currency: number;
    equipment: EquipmentLoadout;
    effects: ActiveEffect[];
    knownCards: string[];
    availableStatPoints: number;
    /**
     * Deckbuilder — extra combat cards earned as play rewards (card
     * ids, duplicates allowed), MERGED into the combat deck on top of the cards
     * derived from `knownCards`. Distinct from `knownCards`: a reward grows the
     * deck (more copies / variety), while learning a card (e.g. via an ethical
     * dilemma) unlocks a new card type. Optional + sparse — absent means none.
     */
    combatRewardCards?: string[];
    /**
     * The GHOST DIE pool (live-tray model). Forged in combat
     * by the FORGE verb; never rerolls; carried ACROSS combats until spent.
     * Written back from `CombatEncounterState.floatingDice` at combat end
     * (`getFloatingDiceColors`). Cap 3. Optional + sparse — absent means none.
     */
    floatingDice?: ('heart' | 'body' | 'mind' | 'wild')[];
    /**
     * Harvest's persistent Soul bank ("the jar travels").
     * Whatever `CombatEncounterState.souls` remains unspent at combat end
     * writes back here (every outcome, same convention as `floatingDice`)
     * instead of evaporating with the rest of per-combat state. Optional +
     * sparse — absent means 0, same as `floatingDice`.
     */
    bankedSouls?: number;
    /**
     * The DIE-GEAR RAIL (Upgradeable Dice): one gear
     * piece per die (heart/body/mind + wild gold), defining each die's face
     * distribution and special payload. The four dice are permanent immutable
     * 6-siders; ALL progression lives here. Deliberately SEPARATE from
     * `EquipmentLoadout` (signet relics and die gear never compete for slots)
     * — its own color-keyed record. Upgraded at the blacksmith (HONE / TEMPER)
     * and by gear swaps. Absent on a fresh or older save; the combat engine and
     * the blacksmith fall back to the frozen `DEFAULT_DIE_GEAR` per color via
     * the single `activeDieGear` seam. Once any upgrade lands (or a save is
     * migrated to v15), this is a full concrete 4-color rail — a real
     * per-save object, so upgrades never mutate the `Object.freeze`d default.
     * Mirrors the sparse-optional precedent of `floatingDice` / `bankedSouls`.
     */
    dieGear?: Partial<Record<'heart' | 'body' | 'mind' | 'wild', UpgradeableDieGear>>;
    /**
     * THE PATH — ACT REWARD DICE. "After each act is
     * completed, the players are rewarded a red/blue/purple base die of their
     * choice." Each is a duplicate colour die rolled into EVERY round's
     * tray on top of the four fixed dice (`rollUpgradeableDice`).
     * Optional + sparse — absent means none. There is no draft, so an extra
     * usable die is an extra PAID play.
     */
    bonusTurnDice?: number;
    /**
     * THE PATH — DIE UPGRADES. How many mana-face
     * upgrades this character's dice carry (0-`MAX_DIE_UPGRADE_LEVEL`); each
     * level HONES one miss face into a mana face (`honedDieGear`). Expensive
     * in the fiction. Optional + sparse — absent means 0. An authored
     * `dieGear` rail (above) always wins over the honed default.
     */
    dieUpgradeLevel?: number;
    /**
     * How many cards this character has REMOVED from their combat
     * deck THIS RUN. Not per node, not lifetime-across-runs: T's "every time
     * the player does this across the game" reads as the campaign the player
     * is in, and a run is the campaign.
     *
     * The escalating removal price reads it (`cardRemovalPrice` —
     * `Cards/card.removal.pricing.ts`), and `removeCardFromCombatDeck`
     * increments it on every accepted removal. Optional + sparse — absent
     * means 0, same convention as `floatingDice` / `bankedSouls`; read it
     * through `cardRemovalsOf` rather than dereferencing, so a fresh save
     * (absent) and a v16-migrated save (materialised 0) answer identically.
     */
    cardRemovals?: number;
}

/**
 * Hypothetical stat point allocation for previewing max VITAE.
 * Each field represents additional points to add to the corresponding base stat.
 */
export interface PreviewAllocation {
    heart: number;
    body: number;
    mind: number;
}

/**
 * Result of previewing stat allocation — computed stats without character mutation.
 */
export interface PreviewResult {
    maxHealth: number;
}
