import { Item, Equipment } from '../Items/types';
import { ActiveEffect } from '../Effects/types';
import { ProcUnlocks } from '../Combat/combat-effects';
import type { UpgradeableDieGear } from '../Combat/combat.encounter.types';

/**
 * A character's worn loadout (Phase 18). Exactly 5 worn pieces across 3 slot
 * kinds: 1 weapon, 1 armor, up to 3 interchangeable accessories. The three
 * accessory positions have no identity — an accessory occupies *an* accessory
 * position; declaration/array order is cosmetic. `accessories.length` is capped
 * at `SLOT_CAPACITY.accessory` (3). Replaces the legacy 7-slot record.
 */
export interface EquipmentLoadout {
    weapon: Equipment | null;
    armor: Equipment | null;
    accessories: Equipment[];
}

/** A fresh, empty loadout (no piece worn in any slot). */
export const emptyLoadout = (): EquipmentLoadout => ({
    weapon: null,
    armor: null,
    accessories: [],
});

/**
 * The three core attributes from which all other character/enemy stats derive.
 *
 * @property heart - Emotion, willpower, charisma. Strong against `body`.
 * @property body  - Physical strength and constitution. Strong against `mind`.
 * @property mind  - Intelligence, reflexes, perception. Strong against `heart`.
 */
export interface BaseStats {
    heart: number;
    body: number;
    mind: number;
}

/**
 * Combat stats derived from BaseStats. Each stance contributes two values:
 * `*Attack` (used in attack rolls) and `*Defense` (used as damage reduction).
 * The legacy `*Card` axis (a carry-over from the removed turn-based card-check
 * combat) was deleted 2026-07-08.
 *
 * `luck` is the average of the three base stats and gates random outcomes.
 */
export interface DerivedStats {
    physicalAttack: number;
    physicalDefense: number;
    mentalAttack: number;
    mentalDefense: number;
    emotionalAttack: number;
    emotionalDefense: number;
    luck: number;
}

/**
 * Out-of-combat stats — saving throws and ability tests. Player-only.
 * Saves resist effects of that stance; tests are general ability checks.
 */
export interface NonCombatStats {
    physicalSave: number;
    physicalTest: number;
    mentalSave: number;
    mentalTest: number;
    emotionalSave: number;
    emotionalTest: number;
}

/**
 * The player character.
 *
 * @property id                     - Stable identifier (Knowledge-Gaps Q12 /
 *                                    Phase 35). Auto-generated by
 *                                    `createCharacter` from `getRng()` when
 *                                    not supplied by the caller. Mirrors
 *                                    `Enemy.id` so `ActiveEffect.sourceId`
 *                                    can unambiguously point at the applier.
 * @property level                  - Determines stat scaling and abilities.
 * @property experience             - Total XP earned.
 * @property experienceToNextLevel  - XP threshold for the next level-up.
 * @property baseStats              - Heart/Body/Mind core attributes.
 * @property derivedStats           - Combat stats derived from baseStats.
 * @property nonCombatStats         - Saves and ability tests.
 * @property inventory              - Items the character is carrying.
 * @property equipment              - The worn `EquipmentLoadout` (Phase 18):
 *                                    1 weapon + 1 armor + ≤3 accessories.
 *                                    Spec 05 Q3: equipment `statModifiers` are
 *                                    folded into `derivedStats` at equip-time,
 *                                    so the character's `derivedStats` is
 *                                    already "post-equipment".
 * @property effects                - Active status effects on the character.
 * @property knownCards            - IDs of cards the character has learned/unlocked.
 *                                    The combat catalogue is the learned set
 *                                    filtered by affordability (ADR-0002 / Phase
 *                                    99); there is no equipped-card loadout gate.
 * @property availableStatPoints    - Unspent stat points awaiting allocation
 *                                    (Spec 06 Q3 + Q8). Granted on level-up,
 *                                    spent via `allocateStatPoint`. Defaults
 *                                    to 0 for preset-built characters since
 *                                    presets ship pre-allocated.
 */
export interface Character {
    id: string;
    name: string;
    level: number;
    experience: number;
    experienceToNextLevel: number;
    health: number;
    maxHealth: number;
    baseStats: BaseStats;
    derivedStats: DerivedStats;
    nonCombatStats: NonCombatStats;
    inventory: Item[];
    /**
     * Spec 08 Q8 — generic in-game currency counter. Spent / earned through the
     * Phase 37 shop reducers (`Items/shop.reducer.ts`).
     */
    currency: number;
    equipment: EquipmentLoadout;
    effects: ActiveEffect[];
    knownCards: string[];
    availableStatPoints: number;
    /**
     * Per-cell Spec 03 proc unlock caps. Defaults to tier 1 in every cell —
     * basic actors only roll the lowest-tier proc table entries. Cards /
     * progression in Spec 04 / 06 raise the cap to unlock T2 / T3 entries.
     */
    procUnlocks?: ProcUnlocks;
    /**
     * Spec 26b deckbuilder — extra combat cards earned as play rewards (card
     * ids, duplicates allowed), MERGED into the combat deck on top of the cards
     * derived from `knownCards`. Distinct from `knownCards`: a reward grows the
     * deck (more copies / variety), while learning a card (e.g. via an ethical
     * dilemma) unlocks a new card type. Optional + sparse — absent means none.
     */
    combatRewardCards?: string[];
    /**
     * Spec 32 v3 §5 — the GHOST DIE pool (live-tray model). Forged in combat
     * by the FORGE verb; never rerolls; carried ACROSS combats until spent.
     * Written back from `CombatEncounterState.floatingDice` at combat end
     * (`getFloatingDiceColors`). Cap 3. Optional + sparse — absent means none.
     */
    floatingDice?: ('heart' | 'body' | 'mind' | 'wild')[];
    /**
     * Phase 32 part 1b — Harvest's persistent Soul bank ("the jar travels").
     * Whatever `CombatEncounterState.souls` remains unspent at combat end
     * writes back here (every outcome, same convention as `floatingDice`)
     * instead of evaporating with the rest of per-combat state. Optional +
     * sparse — absent means 0. No migration needed: a brand-new optional
     * field on an already-permissive save shape, same as `floatingDice`.
     * Milestone-rider design (what a running total unlocks) is deferred —
     * see `plan/phases/phase_32_theme_deep_work.md` Follow-ups.
     */
    bankedSouls?: number;
    /**
     * Spec 33 §6 (Upgradeable Dice, Phase D5) — the DIE-GEAR RAIL: one gear
     * piece per die (heart/body/mind + wild gold), defining each die's face
     * distribution and special payload. The four dice are permanent immutable
     * 6-siders; ALL progression lives here. Deliberately SEPARATE from
     * `EquipmentLoadout` (signet relics and die gear never compete for slots)
     * — its own color-keyed record. Upgraded at the blacksmith (HONE / TEMPER)
     * and by gear swaps. Absent on a fresh/pre-D5 save; the combat engine and
     * the blacksmith fall back to the frozen `DEFAULT_DIE_GEAR` per color via
     * the single `activeDieGear` seam. Once any upgrade lands (or a save is
     * migrated to v15), this is a full concrete 4-color rail — a real
     * per-save object, so upgrades never mutate the `Object.freeze`d default.
     * Mirrors the sparse-optional precedent of `floatingDice` / `bankedSouls`.
     */
    dieGear?: Partial<Record<'heart' | 'body' | 'mind' | 'wild', UpgradeableDieGear>>;
    /**
     * THE PATH (owner ruling 2026-09-02) — ACT REWARD DICE. "After each act is
     * completed, the players are rewarded a red/blue/purple base die of their
     * choice." Extra dice rolled into EVERY turn's tray on top of
     * `TURN_DICE_COUNT`. Optional + sparse — absent means none.
     *
     * MEASURED, NOT ASSUMED (2026-09-02): this is a real axis but a WEAK one.
     * Under the roll-N-draft-ONE law an extra die buys better colour selection
     * and more banked Conviction — it does NOT buy an extra PAID play. Raising
     * a late-stage player from 2 bonus dice to 8 moved the playtest matrix by
     * exactly zero. Making "more dice" mean "more actions" needs the draft
     * model to hand out `1 + bonus` drafts per turn, which is an open design
     * call, not a wiring gap.
     */
    bonusTurnDice?: number;
    /**
     * THE PATH (owner ruling 2026-09-02) — DIE UPGRADES. How many mana-face
     * upgrades this character's dice carry (0-`MAX_DIE_UPGRADE_LEVEL`); raises
     * the share of LIVE then WILD faces in the roll bag (`dieFacesForUpgrade`).
     * Expensive in the fiction. Optional + sparse — absent means 0. The
     * shipping expression is the flag-gated `dieGear` rail above; this is the
     * plain engine knob the same idea reduces to.
     */
    dieUpgradeLevel?: number;
    /**
     * Phase 52a — how many cards this character has REMOVED from their combat
     * deck THIS RUN. Not per node, not lifetime-across-runs: T's "every time
     * the player does this across the game" reads as the campaign the player
     * is in, and a run is the campaign.
     *
     * The escalating removal price reads it (`cardRemovalPrice` —
     * `Cards/card.removal.pricing.ts`), and `removeCardFromCombatDeck`
     * increments it on every accepted removal. Optional + sparse — absent
     * means 0, same convention as `floatingDice` / `bankedSouls`; read it
     * through `cardRemovalsOf` rather than dereferencing, so a fresh save
     * (absent) and a v16-migrated save (materialised 0) answer identically.
     */
    cardRemovals?: number;
}

/**
 * Hypothetical stat point allocation for previewing derived stats.
 * Each field represents additional points to add to the corresponding base stat.
 */
export interface PreviewAllocation {
    heart: number;
    body: number;
    mind: number;
}

/**
 * Result of previewing stat allocation — computed stats without character mutation.
 */
export interface PreviewResult {
    derivedStats: DerivedStats;
    nonCombatStats: NonCombatStats;
    maxHealth: number;
}
