/**
 * Card engine — pure resource and execution helpers for Spec 04.
 *
 * The Hazard-Pattern combat engine drives card bottom-actions through
 * `executeCard`. Every helper here is pure: callers thread the updated state
 * forward themselves.
 *
 * Resource economy (locked 2026-05-11):
 *   - Heart / Body / Mind tokens are generated by basic actions of the
 *     matching stance (attack hit = +3, attack miss = +1, defend = +5).
 *   - Fallacy / Paradox tokens are generated when the player uses a skill
 *     of that category.
 *   - Card costs are spent against the same token pool. Multi-key costs
 *     implicitly require resonance — caller must hold ≥ each cost.
 */

import { Character } from '../Character/types';
import { Enemy } from '../Enemy/types';
import { ActiveEffect, Effect } from '../Effects/types';
import { lookupEffect, applyEffect } from '../Effects';
import { applyDamage, heal } from '../Combat/health';
import { removeRandomBuff } from '../Combat/effects';
import { resolveEffectApplication } from '../Combat/resist';
import { incrementFriendship } from '../Combat/combat.reducer';
import { isBefriendAttemptEligible } from '../Combat/index';
import { Combatant, CombatState, Stance } from '../Combat/types';
import { RESOURCE_GENERATION } from '../Game/game-mechanics.constants';
import { Equipment, EquipmentSlot } from '../Items/types';
import { applyEquipmentGenerationBonus } from '../Items/equipment.engine';
import { applySetGenerationBonus } from '../Items/set.engine';
import {
    CombatResources, Card, CardCategory, CardCombatEffects,
    CardSpecialMechanic,
} from './types';
import { cardLibrary, getCardById } from './cards.library';

// ─── Resource Generation ─────────────────────────────────────────────────────

/**
 * Returns a new `CombatResources` snapshot with the actor's stance token
 * topped up per the resource-generation table:
 *
 *   attack hit  → +3 of stance colour
 *   attack miss → +1 of stance colour
 *   defend      → +5 of stance colour
 *
 * Per Spec 05 Q10 / step 6, the optional `equipment` argument applies any
 * matching `generationBonus` entries from the wearer's equipped items on
 * top of the base table. Items without a `resourceInteraction` contribute
 * nothing — `equipment = undefined` reproduces pre-Spec 05 behaviour.
 *
 * Pure: input snapshot is not mutated.
 */
export function generateBasicActionResources(
    resources: CombatResources,
    stance: Stance,
    outcome: 'hit' | 'miss' | 'defend',
    equipment?: Partial<Record<EquipmentSlot, Equipment>>,
): CombatResources {
    const amount =
        outcome === 'defend' ? RESOURCE_GENERATION.DEFEND
      : outcome === 'hit'    ? RESOURCE_GENERATION.ATTACK_HIT
      :                        RESOURCE_GENERATION.ATTACK_MISS;
    const base: CombatResources = { ...resources, [stance]: resources[stance] + amount };
    if (!equipment) return base;
    // Apply per-item generation bonuses first, then per-set bonuses on top.
    // Both share the same `EquipmentBonusOutcome` semantics and the same ≥0
    // clamp per counter (Spec 05e Q2 — additive, no cap).
    const withItemBonuses = applyEquipmentGenerationBonus(base, equipment, outcome);
    return applySetGenerationBonus(withItemBonuses, equipment, outcome);
}

/**
 * Adds 1 token of the philosophical resource matching the skill's category
 * (Fallacy or Paradox). Called after a skill resolves successfully.
 */
export function generatePhilosophicalResource(
    resources: CombatResources,
    category: CardCategory,
): CombatResources {
    const key: keyof CombatResources = category === 'fallacy' ? 'fallacy' : 'paradox';
    return { ...resources, [key]: resources[key] + 1 };
}

// ─── Damage Calculation ──────────────────────────────────────────────────────

/**
 * Spec 32 v3 §1 — THE STRIKE IS DEAD. `basePower` was deleted from the Card
 * schema, so no card carries a damage/heal magnitude any more: every point of
 * enemy HP falls to DoT ticks, status-payoff bursts, engine-gated drips, or
 * reflect (all combat-engine owned). This function is kept for API
 * compatibility (sim policies / projections multiply by it) and returns 0
 * unconditionally — a card that "deals damage" is now a compile error at the
 * schema and a no-op here.
 */
export function calculateCardDamage(
    _actor: Combatant,
    _skill: Card,
    _target?: Combatant,
): number {
    return 0;
}

/**
 * Returns the philosophical category the skill should generate on use.
 * Tier 1 / 2 skills generate their own category (Fallacy → Fallacy, Paradox
 * → Paradox). Tier 3 skills already consumed a philosophical token to fire,
 * so they generate the OPPOSING type — Fallacy → Paradox, Paradox → Fallacy.
 * This drives the late-combat skill chain described in Spec 04b.
 */
export function philosophicalCategoryFor(skill: Card): CardCategory {
    if (skill.tier === 3) {
        return skill.category === 'fallacy' ? 'paradox' : 'fallacy';
    }
    return skill.category;
}

// ─── Card Learning (Phase 30) ───────────────────────────────────────────────

/**
 * Returns every entry in `cardLibrary` that the character has not already
 * learned. Order matches the library order so the UI can show a stable list
 * across calls. Cards are learnable unconditionally — the legacy
 * learning-requirement gate (level / stat / prerequisite / alignment) was
 * removed 2026-07-08.
 */
export function getAvailableCards(
    character: Pick<Character, 'knownCards'>,
): Card[] {
    return cardLibrary.filter(s => !character.knownCards.includes(s.id));
}

/**
 * Appends `cardId` to `character.knownCards` when the card exists and is not
 * already known. Pure; returns the unchanged character (same reference) on any
 * guard miss.
 */
export function learnCard(
    character: Character,
    cardId: string,
): Character {
    if (character.knownCards.includes(cardId)) return character;
    if (!getCardById(cardId)) return character;
    return {
        ...character,
        knownCards: [...character.knownCards, cardId],
    };
}

// ─── Card Execution ─────────────────────────────────────────────────────────

/** One discrete thing that happened while a skill resolved. */
export type CardEvent =
    | { kind: 'damage';
        cardId: string;
        target: 'self' | 'enemy';
        amount: number;
        hpBefore: number;
        hpAfter: number }
    | { kind: 'heal';
        cardId: string;
        target: 'self' | 'enemy';
        amount: number;
        hpBefore: number;
        hpAfter: number }
    | { kind: 'effect-applied';
        cardId: string;
        appliedTo: 'self' | 'enemy';
        effect: Effect;
        message: string }
    | { kind: 'buff-fumbled';
        cardId: string;
        appliedTo: 'self' | 'enemy';
        effect: Effect;
        message: string }
    | { kind: 'buff-stripped';
        cardId: string;
        target: 'self' | 'enemy';
        effect: Effect | null }
    | { kind: 'buff-converted';
        cardId: string;
        effect: Effect | null;
        message: string }
    | { kind: 'philosophical-generated';
        cardId: string;
        category: CardCategory }
    | { kind: 'synergy-fired';
        cardId: string;
        /** Synergy damage added on top of the skill's base damage.
         *  Already applied to the target by the time this event fires. */
        bonusDamage: number;
        /** Effect ids consumed from caster/target by `consumeMatched`. */
        consumedEffectIds: { caster: string[]; target: string[] };
        /** True if `consumeAllResources` zeroed the pool. */
        consumedAllResources: boolean;
        /** Total tokens consumed (sum of body+mind+heart before the zero). */
        consumedTokens: number;
        /** True if `clearAllEffectsBothSides` swept both sides. */
        clearedAllEffects: boolean }
    | { kind: 'friendship-incremented'; 
        cardId: string; 
        amount: number }
    | { kind: 'befriend-attempted';
        cardId: string;
        successful: boolean;
        message: string };

/** Result of `executeCard`. */
export interface CardResolution {
    state: CombatState;
    events: CardEvent[];
    /** Phase 108 - when true, indicates the skill triggered mercy choice activation */
    activateMercyChoice?: boolean;
}

/** Lookup helper used by `executeCard` to resolve a skill ID against an actor. */
export interface CardLookup {
    (cardId: string): Card | undefined;
}

/**
 * Runs a skill end-to-end against the current `CombatState`:
 *
 *   1. Validate the skill is equipped (player) or in the enemy's rotation.
 *   2. Apply damage / heal based on `targetType`.
 *   3. Resolve each `combatEffects` payload through `resolveEffectApplication`
 *      so resist tier matches the skill's `tier`.
 *   4. Generate one Fallacy or Paradox token from the skill's category.
 *
 * The caller — not this function — is responsible for surfacing the returned
 * `CardEvent[]` to any higher-level event stream.
 *
 * Phase 49 — `casterSide` decides which side is firing the skill. Defaults
 * to `'player'` for back-compat with the pre-Phase-49 call site at
 * `src/Combat/phases/scenario.ts`. When `'enemy'`, the enemy is the caster
 * and the player is the target; `skill.targetType` is interpreted relative
 * to the caster (`'self'` → caster's effects; `'enemy'` → opposing side).
 * Enemy-cast skills are validated against `Enemy.skills?` rather than
 * `Character.knownCards`. Resource handling stays uniform — the caller
 * is responsible for passing a sentinel `combatResources` for the enemy
 * path (per D2 in plan/phases/phase_49_enemy_skill_caster.md).
 *
 * @throws if the skill is not known (player path) or not in the enemy's
 *   rotation (enemy path), or not found in the lookup.
 */
export function executeCard(
    state: CombatState,
    cardId: string,
    lookupCard: CardLookup,
    casterSide: 'player' | 'enemy' = 'player',
): CardResolution {
    const isPlayerCaster = casterSide === 'player';
    const caster: Combatant = isPlayerCaster ? state.player : state.enemy;
    const target: Combatant = isPlayerCaster ? state.enemy : state.player;

    if (isPlayerCaster) {
        // A player OWNS a combat card when it is a learned skill OR a card-reward
        // pickup — the exact two sources `buildCombatDeck` deals from. Reward
        // cards (`combatRewardCards`) enter the deck WITHOUT joining `knownCards`
        // (they bypass the learning gate — the won combat is the gate), so a
        // knownCards-only check wrongly rejected legitimately-dealt reward cards
        // and crashed combat when one was played.
        const playerCaster = caster as Character;
        const owned = playerCaster.knownCards.includes(cardId)
            || (playerCaster.combatRewardCards ?? []).includes(cardId);
        if (!owned) {
            throw new Error(`Card '${cardId}' is not known.`);
        }
    } else {
        const rotation = (caster as Enemy).skills ?? [];
        if (!rotation.some(s => s.id === cardId)) {
            throw new Error(`Card '${cardId}' is not in the enemy's rotation.`);
        }
    }

    const skill = lookupCard(cardId);
    if (!skill) {
        throw new Error(`Card '${cardId}' not found in library.`);
    }

    const events: CardEvent[] = [];

    let workingCaster: Combatant = caster;
    let workingTarget: Combatant = target;

    // Phase 93: Only apply damage resistance for enemy-targeting skills
    // Self-targeting skills (heals) shouldn't have resistance applied
    const resistanceTarget = skill.targetType === 'enemy' ? workingTarget : undefined;
    const damage = calculateCardDamage(workingCaster, skill, resistanceTarget);

    // Phase 66 — synergy clause. Evaluate predicate against the
    // pre-damage effects pool (so the matched effect's intensity /
    // duration still reflects the field-state the caster saw); apply
    // synergy damage on top of the base damage; then run any
    // side-effects (consume matched / consume all resources / clear
    // both sides / apply effect on fire). Per D7, this happens before
    // the skill's own `combatEffects` apply.
    let synergyForceResources: CombatResources | null = null;
    if (skill.synergy) {
        const syn = skill.synergy;
        const pool = syn.predicate?.on === 'caster' ? workingCaster.effects : workingTarget.effects;
        const matched = syn.predicate
            ? pool.find(e =>
                e.effectId === syn.predicate!.effectId
                && (syn.predicate!.intensityMin === undefined || (e.intensity ?? 0) >= syn.predicate!.intensityMin)
                && (syn.predicate!.durationMin === undefined || (e.remainingDuration ?? 0) >= syn.predicate!.durationMin)
            ) ?? null
            : null;
        const fired = !syn.predicate || matched !== null;
        if (fired) {
            const consumedTokens = syn.consumeAllResources
                ? state.combatResources.body + state.combatResources.mind + state.combatResources.heart
                : 0;
            const bonusDamage =
                (syn.bonusDamage ?? 0)
                + (matched ? (matched.intensity ?? 0) * (syn.intensityDamageMul ?? 0) : 0)
                + (matched ? (matched.remainingDuration ?? 0) * (syn.durationDamageMul ?? 0) : 0)
                + consumedTokens * (syn.resourceTokenDamageMul ?? 0);

            // Apply synergy damage to the same side as the skill's
            // primary damage (enemy-targeted skills hit the enemy;
            // self-targeted skills heal the caster).
            if (bonusDamage > 0) {
                if (skill.targetType === 'enemy') {
                    workingTarget = applyDamage(workingTarget, bonusDamage);
                } else {
                    workingCaster = heal(workingCaster, bonusDamage);
                }
            }

            // consumeMatched — clear the matched ActiveEffect.
            const consumedEffectIds: { caster: string[]; target: string[] } = { caster: [], target: [] };
            if (syn.consumeMatched && matched && syn.predicate) {
                if (syn.predicate.on === 'caster') {
                    workingCaster = { ...workingCaster, effects: workingCaster.effects.filter(e => e !== matched) };
                    consumedEffectIds.caster.push(matched.effectId);
                } else {
                    workingTarget = { ...workingTarget, effects: workingTarget.effects.filter(e => e !== matched) };
                    consumedEffectIds.target.push(matched.effectId);
                }
            }

            // clearAllEffectsBothSides — clear every ActiveEffect on
            // both combatants. Per D9 this includes Phase 60 set-bonus
            // passives (sourceId: 'set-bonus', remainingDuration: -1).
            if (syn.clearAllEffectsBothSides) {
                workingCaster = { ...workingCaster, effects: [] };
                workingTarget = { ...workingTarget, effects: [] };
            }

            // applyEffectOnFire — apply the additional effect on the
            // caster. Uses the same applyCardEffect path the rest of
            // the engine uses (so resist / rebound / stacking semantics
            // are honoured).
            if (syn.applyEffectOnFire) {
                const result = applyCardEffect(
                    syn.applyEffectOnFire, skill, workingCaster, workingTarget, state.round,
                );
                workingCaster = result.caster;
                workingTarget = result.target;
                events.push(...result.events);
            }

            // consumeAllResources — zero out the pool. Tracked locally so the
            // generation step below starts from an emptied pool.
            if (syn.consumeAllResources) {
                synergyForceResources = { body: 0, mind: 0, heart: 0, fallacy: 0, paradox: 0 };
            }

            events.push({
                kind: 'synergy-fired', cardId,
                bonusDamage,
                consumedEffectIds,
                consumedAllResources: syn.consumeAllResources ?? false,
                consumedTokens,
                clearedAllEffects: syn.clearAllEffectsBothSides ?? false,
            });
        }
    }

    if (damage > 0) {
        if (skill.targetType === 'enemy') {
            const hpBefore = workingTarget.health;
            workingTarget = applyDamage(workingTarget, damage);
            events.push({
                kind: 'damage', cardId, target: 'enemy',
                amount: damage, hpBefore, hpAfter: workingTarget.health,
            });
        } else {
            const hpBefore = workingCaster.health;
            workingCaster = heal(workingCaster, damage);
            events.push({
                kind: 'heal', cardId, target: 'self',
                amount: damage, hpBefore, hpAfter: workingCaster.health,
            });
        }
    }

    for (const payload of skill.combatEffects ?? []) {
        const result = applyCardEffect(
            payload, skill, workingCaster, workingTarget, state.round,
        );
        workingCaster = result.caster;
        workingTarget = result.target;
        events.push(...result.events);
    }

    for (const mechanic of skill.specialMechanics ?? []) {
        const result = applySpecialMechanic(
            mechanic, skill, workingCaster, workingTarget, state.round, state,
        );
        workingCaster = result.caster;
        workingTarget = result.target;
        events.push(...result.events);
    }

    // Phase 91 — friendship increment processing
    let workingState = {
        ...state,
        player: (isPlayerCaster ? workingCaster : workingTarget) as Character,
        enemy: (isPlayerCaster ? workingTarget : workingCaster) as Enemy,
    };
    if (skill.incrementsFriendship && skill.incrementsFriendship > 0) {
        for (let i = 0; i < skill.incrementsFriendship; i++) {
            workingState = incrementFriendship(workingState);
        }
        events.push({ 
            kind: 'friendship-incremented', 
            cardId, 
            amount: skill.incrementsFriendship 
        });
    }

    const genCategory = philosophicalCategoryFor(skill);
    // Cards carry no resource cost (de-tokenized): the working pool passes
    // through unchanged, except when synergy's `consumeAllResources` zeroed it.
    // The philosophical-category generation still fires (+1 fallacy/paradox).
    const baseAfterCost = synergyForceResources ?? workingState.combatResources;
    const nextResources = generatePhilosophicalResource(baseAfterCost, genCategory);
    events.push({ kind: 'philosophical-generated', cardId, category: genCategory });

    const nextPlayer = (isPlayerCaster ? workingCaster : workingTarget) as Character;
    const nextEnemy  = (isPlayerCaster ? workingTarget : workingCaster) as Enemy;

    // Phase 108 — Check for successful befriend attempts to activate mercy choice
    const successfulBefriend = events.find(
        e => e.kind === 'befriend-attempted' && e.successful
    );
    const activateMercyChoice = Boolean(successfulBefriend);

    return {
        state: {
            ...workingState,
            player: nextPlayer,
            enemy:  nextEnemy,
            combatResources: nextResources,
        },
        events,
        activateMercyChoice,
    };
}

interface CardEffectResult {
    caster: Combatant;
    target: Combatant;
    events: CardEvent[];
}

/**
 * Routes a single `CardCombatEffects` payload through the Spec 03
 * `resolveEffectApplication` resolver and lands the outcome on the correct
 * combatant. Tier-driven resist behaviour is inherited from the underlying
 * effect definition (Tier 1 auto, Tier 2 resisted, Tier 3 nat-20 only).
 *
 * `payload.intensity` and `payload.duration` override the effect's default
 * stack/duration so skills like Liar's Echo (+2 intensity, 2-round mark) and
 * Sorites' Cascade (intensity-2 bleed) can lean on the same library entry as
 * the proc system without warping the underlying effect definition.
 *
 * Phase 49 — caster-agnostic. `payload.appliedTo === 'self'` routes to
 * `caster.effects`; `'enemy'` routes to `target.effects` (the opposing
 * side, regardless of which Combatant subtype that is).
 */
function applyCardEffect(
    payload: CardCombatEffects,
    skill: Card,
    caster: Combatant,
    target: Combatant,
    round: number,
): CardEffectResult {
    const events: CardEvent[] = [];
    const effect = lookupEffect(payload.effectId);
    if (!effect) {
        return { caster, target, events };
    }

    const targetIsSelf = payload.appliedTo === 'self';
    const effectTarget: Combatant = targetIsSelf ? caster : target;
    const intensityOverride = payload.intensity;
    const durationOverride  = payload.duration;

    const built = buildActiveEffect(effect, round, intensityOverride, durationOverride);
    const result = resolveEffectApplication(
        effectTarget,
        built,
        effect.type,
        caster.baseStats.heart,
    );

    // When the skill payload explicitly overrides duration we must apply in
    // `additive` mode so the override survives the apply path, which otherwise
    // resets to `effect.duration` on first application. The override value is
    // also the value to write.
    const buildApplyOptions = (intensity: number, duration: number) => {
        if (durationOverride !== undefined) {
            return {
                intensityDelta: intensity,
                durationMode:   'additive' as const,
                durationDelta:  duration,
            };
        }
        return {
            intensityDelta: intensity,
            durationDelta:  duration,
        };
    };

    if (!result.success) {
        events.push({
            kind: 'buff-fumbled', cardId: skill.id,
            appliedTo: targetIsSelf ? 'self' : 'enemy',
            effect, message: result.message,
        });
        return { caster, target, events };
    }

    const appliedIntensity = result.activeEffect?.intensity ?? intensityOverride ?? 1;
    const appliedDuration  = result.activeEffect?.remainingDuration ?? durationOverride ?? effect.duration;

    const applied = applyEffect(
        effectTarget.effects, effect, round,
        { ...buildApplyOptions(appliedIntensity, appliedDuration), sourceId: caster.id },
    );

    events.push({
        kind: 'effect-applied', cardId: skill.id,
        appliedTo: targetIsSelf ? 'self' : 'enemy',
        effect, message: result.message,
    });

    if (targetIsSelf) {
        return {
            caster: { ...caster, effects: applied.activeEffects } as Combatant,
            target,
            events,
        };
    }
    return {
        caster,
        target: { ...target, effects: applied.activeEffects } as Combatant,
        events,
    };
}

function buildActiveEffect(
    effect: Effect,
    round: number,
    intensityOverride?: number,
    durationOverride?: number,
): ActiveEffect {
    return {
        effectId:          effect.id,
        remainingDuration: durationOverride  ?? effect.duration,
        intensity:         intensityOverride ?? 1,
        appliedAt:         round,
        tier:              effect.tier,
        resistedBy:        effect.resistedBy,
        resistDR:          effect.resistDR,
    };
}

// ─── Special Mechanics ───────────────────────────────────────────────────────

/**
 * Resolves a `CardSpecialMechanic` (buff-strip, conversion, secondary heal,
 * etc.) against the current working player / enemy snapshots and returns the
 * updated snapshots plus any `CardEvent`s the resolver should forward to
 * the combat event stream.
 *
 * Mechanics run AFTER `combatEffects` so that, for example, Ship of Theseus
 * sees the same buff list a player can observe in the CLI before this round
 * resolves.
 */
function applySpecialMechanic(
    mechanic: CardSpecialMechanic,
    skill: Card,
    caster: Combatant,
    target: Combatant,
    round: number,
    state: CombatState,
): CardEffectResult {
    const events: CardEvent[] = [];

    switch (mechanic.kind) {
        case 'strip_random_buff': {
            if (mechanic.appliedTo === 'enemy') {
                const { target: nextTarget, removed } = removeRandomBuff(target);
                events.push({
                    kind: 'buff-stripped', cardId: skill.id, target: 'enemy',
                    effect: removed ? lookupEffect(removed.effectId) ?? null : null,
                });
                return { caster, target: nextTarget, events };
            }
            const { target: nextCaster, removed } = removeRandomBuff(caster);
            events.push({
                kind: 'buff-stripped', cardId: skill.id, target: 'self',
                effect: removed ? lookupEffect(removed.effectId) ?? null : null,
            });
            return { caster: nextCaster, target, events };
        }

        case 'befriend_attempt': {
            // Phase 108 — Check if befriend attempt is valid
            const isEligible = isBefriendAttemptEligible(state);
            
            if (!isEligible) {
                events.push({
                    kind: 'befriend-attempted',
                    cardId: skill.id,
                    successful: false,
                    message: 'Befriend failed: enemy not yet vulnerable to mercy.',
                });
                return { caster, target, events };
            }

            // Successful befriend attempt - opens mercy choice
            events.push({
                kind: 'befriend-attempted',
                cardId: skill.id,
                successful: true,
                message: 'Befriend successful! Choose mercy or exploitation.',
            });
            return { caster, target, events };
        }

        // ── Hazard-Pattern / spec 32 v3 card mechanics ───────────────────────
        // Every other mechanic kind is COMBAT-ENGINE OWNED: the skill engine
        // no-ops it (so the shared effect machinery stays untouched) and the
        // HP-model combat engine reads the mechanic at its `playBottomAction` /
        // `resolveThreatPhase` / `processBetweenPhases` call sites.
        default:
            return { caster, target, events };
    }
}
