/**
 * Cards System Types
 * Cards come in two categories: fallacies and paradoxes, and run on a five-
 * resource resonance economy (heart / body / mind / fallacy / paradox). See
 * `specs/04-cards-engine.md` for the full economy design.
 */

import type { CardTheme } from './card-themes';

/**
 * Philosophical aspect alignment for cards
 * Determines which base stat the card scales with and which combat type it uses.
 * - 'body': Physical/strength-based cards
 * - 'mind': Mental/intelligence-based cards
 * - 'heart': Emotional/charisma-based cards
 */
export type StatType = 'body' | 'mind' | 'heart';

/**
 * Card category type
 * - 'fallacy': Cards based on logical fallacies (generate ⚖ on use)
 * - 'paradox': Cards based on philosophical paradoxes (generate ∞ on use)
 */
export type CardCategory = 'fallacy' | 'paradox';

/**
 * Tier of a card — mirrors the effect tier system. Drives the resist tier
 * used when a card applies a `combatEffects` payload through the Spec 03
 * machinery (Tier 1 auto-applies, Tier 2 resisted, Tier 3 only nat-20 repels).
 */
export type CardTier = 1 | 2 | 3;

/**
 * Spec 32 v3 — the rank ladder (quality axis, distinct from `tier`):
 * 1 Doxa · 2 Lemma · 3 Thesis · 4 Theorem · 5 Axiom · 6 Aporia.
 */
export type CardRank = 1 | 2 | 3 | 4 | 5 | 6;

/** Display names for the rank ladder (printed on card faces). */
export const CARD_RANK_NAMES: Readonly<Record<CardRank, string>> = Object.freeze({
    1: 'Doxa', 2: 'Lemma', 3: 'Thesis', 4: 'Theorem', 5: 'Axiom', 6: 'Aporia',
});

/** Spec 32 v3 — rarity band, derived from rank (§4). Drives the deck recipe
 *  and reward drop weights. */
export type CardRarity = 'common' | 'uncommon' | 'rare';

/** Maps a rank to its rarity band: common = Doxa/Lemma, uncommon =
 *  Thesis/Theorem, rare = Axiom/Aporia. */
export function rankToRarity(rank: CardRank): CardRarity {
    return rank <= 2 ? 'common' : rank <= 4 ? 'uncommon' : 'rare';
}

/**
 * Spec 32 v3 — card type. Open enum (more types to come).
 * - `spell`       — play → discard; recycled by the reshuffle law.
 * - `enchantment` — POSITIVE passive, player-side. Spec 32 v4: FREE line = a TIMED
 *                   instance (3 rounds, dieless); PAID line = the same passive made
 *                   permanent (rest of combat, unique, leaves the deck cycle).
 * - `disenchant`  — NEGATIVE passive attached to the ENEMY. Same FREE-timed / PAID-
 *                   permanent split as `enchantment`.
 */
export type CardType = 'spell' | 'enchantment' | 'disenchant';

/**
 * Targeting scope for a card effect.
 * - `'self'`  — the caster.
 * - `'enemy'` — the current opponent.
 * Multi-combatant targeting is deferred to Spec 07.
 */
export type CardTarget = 'self' | 'enemy';

/**
 * Per-combat player resource counters live on `CombatState`. Seeded at combat
 * start from item/set grants, generated by player basic actions (heart/body/mind
 * from stance attacks/defends), and by player card use (fallacy/paradox from
 * card category/tier). Character carries `knownCards` as the combat catalogue
 * (ADR-0002 / Phase 99 \u2014 there is no equipped-card loadout gate).
 * `knownCards` is not a persistent mana/resource pool.
 */
export interface CombatResources {
    heart: number;
    body: number;
    mind: number;
    fallacy: number;
    paradox: number;
}

/**
 * Combat effect payload applied by a card. Routes through
 * `resolveEffectApplication` (Spec 03) so resist / repel / crit follow the
 * same rules as proc-applied effects.
 *
 * @property effectId    - ID of the effect in the global effects library.
 * @property appliedTo   - 'self' or 'opponent' (relative to the caster).
 * @property description - Display text for the CLI / UI.
 * @property intensity   - Optional initial intensity override (default 1).
 *                         Used by cards like Liar's Echo that stack a Tier 1
 *                         mark with extra intensity on first application.
 * @property duration    - Optional remaining-duration override (defaults to
 *                         the effect's library duration). Switches the apply
 *                         path into `additive` duration mode so the override
 *                         survives stacking.
 */
export interface CardCombatEffects {
    effectId: string;
    appliedTo: 'self' | 'opponent';
    description?: string;
    intensity?: number;
    duration?: number;
}

/**
 * Bespoke card mechanics that don't map cleanly onto an ActiveEffect
 * payload. Each is processed by `executeCard` after `combatEffects`
 * (spec 32 v3: there is no damage step — the strike is dead). Kept as a
 * discriminated union so the resolver / UI can branch on `kind` without
 * runtime tag parsing.
 *
 * - `strip_random_buff`: remove one random buff from the target.
 * - `befriend_attempt`: Phase 108 - attempt to befriend the enemy, opening
 *   a mercy choice state if successful (requires HP gate eligibility).
 */
export type CardSpecialMechanic =
    | { kind: 'strip_random_buff'; appliedTo: 'self' | 'enemy' }
    | { kind: 'befriend_attempt' }
    /** Hazard-Pattern Combat — grants the player GUARD (a shield that absorbs the
     *  enemy's next telegraphed threat). Handled by the combat engine, not the
     *  card engine. `amount` is the base Guard before read/free scaling. */
    | { kind: 'guard'; amount: number }
    /** RUPTURE — consume ALL afflictions on the foe and detonate: 1.5× the
     *  remaining DoT fuel + a flat amount per non-DoT affliction stack (read +
     *  vulnerable scaled, capped at `RUPTURE_BURST_CAP`). `bonusPct` is an extra
     *  flat fraction; `fuelPerPip` adds fuel per pip spent by a paired
     *  `spend_all_pips`; `fuelPerOmenHit` adds fuel per omen hit this combat
     *  (Oracle capstone). HP behavior owned by the combat engine (mirrors
     *  `guard`); the card engine no-ops it. */
    | { kind: 'rupture'; bonusPct?: number; fuelPerPip?: number; fuelPerOmenHit?: number }
    /** SIPHON — heal the player for `pct` of the HP this card erodes from the
     *  foe (rupture/reap bursts). Combat-engine owned. */
    | { kind: 'siphon'; pct: number }
    /** BARRIER — add `amount` (read-scaled) to the player's STACKING, persistent
     *  damage soak (`CombatEncounterState.barrier`), distinct from one-shot GUARD.
     *  Combat-engine owned. */
    | { kind: 'barrier'; amount: number }
    /** RIPOSTE — arm the counter-stance: while armed this phase, an attack your
     *  Guard/Barrier FULLY blocks is answered for `damage` HP (reflect-class,
     *  spec 32 v3 §1 source 4). `reduce` shaves the incoming hit first (the
     *  parry half). Combat-engine owned. */
    | { kind: 'riposte'; damage: number; reduce: number }
    // ── Fate Engine P1 (spec 31 §4.1) — die-manipulation verbs, all combat-engine
    //    owned (the card engine no-ops them, mirroring guard/rupture). ──────────
    /** REROLL_SPENT — re-roll every spent/blocked die in the tray (the library
     *  sibling of the Press Fate signature). Floating dice are exempt. */
    | { kind: 'reroll_spent' }
    /** REFRESH_DIE — the powering die returns to `available` after this play
     *  (independent of the variety-chain rule). */
    | { kind: 'refresh_die' }
    /** CONVERT_DIE_COLOR — the powering die returns REFRESHED as a WILD die. */
    | { kind: 'convert_die_color' }
    /** KINDLE (spec 32 v3) — forge a fresh TEMPORARY die of `color` (this combat
     *  only). It joins the RESERVE at 0 pips when a slot is free; otherwise it
     *  burns for +1 Conviction. */
    | { kind: 'create_temporary_die'; color: 'heart' | 'body' | 'mind' | 'wild' }
    /** PIP — every die currently in the Reserve ripens +`count` pips. */
    | { kind: 'grant_pip'; count: number }
    /** BANK_SPENT_DIE — instead of being spent, the powering die goes to the
     *  Reserve at 0 pips (if a slot is free; otherwise it is spent normally). */
    | { kind: 'bank_spent_die' }
    // ── Spec 32 v3 — the themed-deck verb set (all combat-engine owned) ────────
    /** FORGE — create a FLOATING die: joins the tray now, never rerolls, persists
     *  across rounds AND combats, gone forever when spent. Cap 3; forging at cap
     *  converts to +1 Conviction (printed). `color: 'powering'` = the powering
     *  die's color; `'wild'` on premium cards. */
    | { kind: 'forge_floating_die'; color: 'powering' | 'wild' }
    /** TRANSMUTE (dice-law 2026-07-09) — convert one dead X die in the tray into
     *  a FLOATING WILD die (all floating rules apply: joins the tray now, never
     *  rerolls, persists across combats, gone forever when spent). With no X in
     *  the tray, or at the floating cap, it burns for +1 Conviction (printed). */
    | { kind: 'float_x_die' }
    /** STAGGER — remove `rungs` rungs from the enemy's next telegraphed action;
     *  at 0 rungs the action is denied outright. */
    | { kind: 'stagger'; rungs: number }
    /** LOCK STANCE — the enemy's NEXT phase keeps its current stance (revealed). */
    | { kind: 'lock_stance' }
    /** FORETELL — look at the top `count` cards of your deck (the engine
     *  deterministically floats the highest-rank card to the top) and glimpse
     *  the enemy's next telegraph. */
    | { kind: 'foretell'; count: number }
    /** OMEN — cast the powering die as the prognostication: if the enemy's NEXT
     *  phase stance matches the powering die's stance (wild = this card's
     *  stance), the omen HITS at the next phase boundary and `rider` fires free. */
    | { kind: 'omen'; rider: CardRider }
    /** PREMISE — add `count` Premises to the running tally (Peroration theme). */
    | { kind: 'premise'; count: number }
    /** PERORATION — declare the conclusion (one in play at a time): when the
     *  Premise tally reaches `at`, `rider` fires FREE and the tally resets.
     *  If the tally reaches `concedeAt` first, the enemy CONCEDES the argument
     *  outright (alt-win, spec 32 v3 §9). */
    | { kind: 'peroration'; at: number; rider: CardRider; concedeAt?: number }
    /** SPEND PREMISES — cash the whole tally early: +1 MARK stack per
     *  `markPer` spent and draw 1 per `drawPer` spent. */
    | { kind: 'spend_premises'; markPer: number; drawPer: number }
    /** SPEND ALL PIPS — zero every pip on the powering die + Reserve; a paired
     *  `rupture` gains `fuelPerPip` per pip, and each pip grants `guardPerPip`. */
    | { kind: 'spend_all_pips'; guardPerPip?: number }
    /** RECOIL — pay `hp` VITAE (unpreventable, printed cost). */
    | { kind: 'recoil'; hp: number }
    /** EXTEND DOTS — +`turns` duration to ALL your DoTs on the enemy. */
    | { kind: 'extend_dots'; turns: number }
    /** CONVERT DOTS — convert enemy bleed↔poison at equal intensity,
     *  +`bonusIntensity` (the wound becomes the argument). */
    | { kind: 'convert_dots'; bonusIntensity: number }
    /** BOOST ALL DOTS — +`intensity` to every DoT already on the enemy. */
    | { kind: 'boost_all_dots'; intensity: number }
    /** SOUL — gain `count` Souls (Harvest theme currency). */
    | { kind: 'soul_gain'; count: number }
    /** CONSUME AFFLICTION — consume 1 enemy affliction early: its remaining DoT
     *  fuel ticks NOW, and the harvest yields `souls` Souls. */
    | { kind: 'consume_affliction'; souls: number }
    /** REAP — spend `cost` Souls (fizzles when underfunded): fire `rider`,
     *  and/or KINDLE a die of `kindle` color. */
    | { kind: 'reap'; cost: number; rider?: CardRider; kindle?: 'heart' | 'body' | 'mind' | 'wild' }
    /** REAP ALL — spend every Soul: burst `burstPerSoul` HP per Soul spent
     *  (mechanic-damage path, capped at `RUPTURE_BURST_CAP`). */
    | { kind: 'reap_all'; burstPerSoul: number }
    /** SWAY — add `amount` SWAY to the enemy. SWAY decays 1/turn; if SWAY ≥ the
     *  enemy's current HP at a turn boundary, it CAPITULATES (alt-win). */
    | { kind: 'sway'; amount: number }
    /** ECHO — this card's PAID payload fires twice. */
    | { kind: 'echo' }
    /** ECHO NEXT — your next spell this turn gains ECHO. */
    | { kind: 'echo_next_spell' }
    /** REPRISE — return `count` cards from the discard pile to hand (the engine
     *  picks the highest-rank). `fireFree` also fires the reprised card's FREE
     *  line immediately. */
    | { kind: 'reprise'; count: number; fireFree?: boolean }
    /** REPLAY LAST — replay the PAID payload of the last spell you played this
     *  combat, `times` times (never chains into another replay). */
    | { kind: 'replay_last'; times: number }
    /** CONJURE — create a one-use Thoughtform card into hand (removed from the
     *  combat after it is played or the combat ends). */
    | { kind: 'conjure_card'; cardId: string }
    /** RIDER — an UNCONDITIONAL rider fired by the PAID line (the generic
     *  draw/heal/cleanse/guard verb carrier; same executor as condition riders). */
    | { kind: 'rider'; rider: CardRider };

/**
 * Fate Engine P1 — a card RIDER: a bundle of real-unit bonuses fired by a
 * die-interaction line (`threshold` / `dieBonus` / `fate`). Every field is an
 * exact engine unit so generated action text is the applied number (P0-truth
 * law). All fields optional; absent = 0/false.
 */
export interface CardRider {
    /** +N intensity on the statuses THIS play lands on the enemy. */
    bonusIntensity?: number;
    /** +N turns on the statuses THIS play lands on the enemy. */
    bonusDuration?: number;
    /** +N Guard. */
    guard?: number;
    /** +N Conviction (clamped to the cap). */
    conviction?: number;
    /** Refresh the powering die back to available. */
    refreshDie?: boolean;
    /** Reveal the NEXT threat phase's hidden stance. */
    revealStance?: boolean;
    /** Immediately tick every enemy DoT once (extra tick — durations untouched). */
    tickAllDots?: boolean;
    /** TICK (spec 32 v3) — the strongest enemy DoT deals its per-turn damage
     *  NOW, duration untouched. The canonical small erosion line. */
    tickOne?: boolean;
    /** Cleanse up to N of the player's own debuffs (tier-3 scope). */
    cleanse?: number;
    /** Heal the player N HP. */
    healHp?: number;
    /** Draw N cards. */
    drawCards?: number;
    // ── Spec 32 v3 — themed-deck rider verbs ─────────────────────────────────
    /** +N Premises (Peroration tally). */
    premises?: number;
    /** +N SWAY on the enemy. */
    sway?: number;
    /** +N Souls (Harvest currency). */
    souls?: number;
    /** FORETELL N — reorder the top N of your deck + glimpse the next telegraph. */
    foretell?: number;
    /** Apply an effect from the library (the generic small-status line, e.g.
     *  a FREE "mark d2"). `to` defaults to 'opponent'. */
    applyEffect?: { effectId: string; intensity?: number; duration?: number; to?: 'self' | 'opponent' };
    /** Consume ALL enemy MARK stacks and burst N HP per stack (the-closing-word's
     *  conclusion — an affliction-payoff, mechanic-damage path). */
    ruptureMarks?: number;
    /** +1 intensity to ONE enemy DoT per pip spent (paired with spend verbs). */
    intensityPerPip?: number;
    /** +N pips to every Reserve die (the ripening rider). */
    pips?: number;
    /** STAGGER N — remove N rungs from the enemy's next telegraphed action. */
    stagger?: number;
}

/**
 * Phase 66 — synergy predicate. The matched ActiveEffect on `on`
 * satisfies the predicate when its `effectId` matches AND its
 * `intensity` >= `intensityMin` (if set) AND its `remainingDuration`
 * >= `durationMin` (if set).
 */
export interface SynergyPredicate {
    effectId: string;
    on: 'caster' | 'target';
    intensityMin?: number;
    durationMin?: number;
}

/**
 * Phase 66 — Tier 2 synergy clause. Optional payload on `Card` that
 * rewards stance-switching by conditioning damage / effect application
 * on the presence of an ActiveEffect already on the field (or, for
 * Resonance Detonation, on the unconditional cast).
 *
 * Synergy damage (added to the card's base damage; doesn't replace):
 * ```
 * synergyDamage = bonusDamage
 *               + matched.intensity            × intensityDamageMul
 *               + matched.remainingDuration    × durationDamageMul
 *               + consumedTokens               × resourceTokenDamageMul
 * ```
 *
 * Side effects (in resolution order):
 *   1. `consumeAllResources` zeros the caster's `combatResources` pool
 *      and captures `consumedTokens = body + mind + heart` for the
 *      damage formula.
 *   2. Synergy damage applies to the target.
 *   3. `consumeMatched` clears the matched ActiveEffect on the
 *      predicate's `on` side.
 *   4. `clearAllEffectsBothSides` clears all ActiveEffects on both
 *      combatants (Phase 60 set-bonus passives included — design
 *      intent per Phase 66 D9).
 *   5. `applyEffectOnFire` applies a fresh effect (typically used to
 *      "swap type" — body Thorns → heart Bat-Swarm-Thoughtform).
 *
 * Synergy runs in `executeCard` AFTER `calculateCardDamage` but
 * BEFORE the card's own `combatEffects` apply, so consumed effects
 * don't get post-fire effects layered on top.
 */
export interface CardSynergy {
    /** Optional predicate. If absent, the synergy fires unconditionally
     *  when the card is cast (used by Resonance Detonation per D6). */
    predicate?: SynergyPredicate;
    /** Flat bonus damage on match. */
    bonusDamage?: number;
    /** Multiplier × matched effect's `remainingDuration`. */
    durationDamageMul?: number;
    /** Multiplier × matched effect's `intensity`. */
    intensityDamageMul?: number;
    /** Multiplier × total consumed combat-resource tokens (only fires
     *  when `consumeAllResources` is true). */
    resourceTokenDamageMul?: number;
    /** Clear the matched effect from the predicate's `on` side. */
    consumeMatched?: boolean;
    /** Zero the caster's full `combatResources` pool. */
    consumeAllResources?: boolean;
    /** Clear all ActiveEffects from both combatants. */
    clearAllEffectsBothSides?: boolean;
    /** Apply an additional effect on the caster when synergy fires. */
    applyEffectOnFire?: CardCombatEffects;
}

/**
 * Card entity — an ability that can be learned/unlocked and used in combat.
 *
 * @property id              - Unique identifier for this card.
 * @property name            - Display name.
 * @property description     - Flavor text or lore.
 * @property category        - Fallacy or paradox (drives the philosophical
 *                             token generated on use).
 * @property philosophicalAspect - Stat alignment of the card (heart/body/mind).
 * @property tier            - 1 / 2 / 3, mirrors the effect tier system.
 * @property targetType      - 'self' or 'enemy'.
 * @property combatEffects   - Optional list of effect payloads to apply.
 * @property specialMechanics - Optional bespoke behaviours. Resolved after
 *                              `combatEffects`. (Spec 32 v3: there is NO
 *                              damage step — `basePower` was deleted from the
 *                              schema; raw HP damage is a compile error.)
 */
export interface Card {
    id: string;
    name: string;
    category: CardCategory;
    philosophicalAspect: StatType;
    description: string;
    tier: CardTier;
    targetType: CardTarget;
    /**
     * Spec 32 v3 — the RANK ladder (quality axis): 1 Doxa · 2 Lemma · 3 Thesis
     * · 4 Theorem · 5 Axiom · 6 Aporia. Rarity derives from it (§4):
     * common = 1-2, uncommon = 3-4, rare = 5-6. Orthogonal to `tier` (resist).
     */
    rank: CardRank;
    /**
     * Spec 32 v3 — card type. `spell` plays → discard (FREE + PAID lines).
     * Spec 32 v4 — `enchantment` / `disenchant` now carry BOTH lines: the FREE
     * (dieless) line grants a TIMED instance of the passive (3 rounds); the PAID
     * line makes the same passive permanent (rest of combat), unique-in-play, and
     * leaves the deck cycle. The enchantment sits player-side; the disenchant
     * attaches to the ENEMY as a standing curse.
     */
    cardType: CardType;
    /**
     * Spec 32 — the card's THEME (one of ten). A theme is a family of keywords
     * ({@link CardTheme} / `THEME_KEYWORDS`): the two hallmark keywords plus the utility
     * keywords it synergises with. Drives the catalog's theme/keyword search.
     * Every library card declares one; optional only so throwaway test fixtures
     * need not (the curated-library suite asserts real cards carry it).
     */
    theme?: CardTheme;
    /**
     * Spec 32 v3 — the authored FREE (dieless) line for SPELLS. Budget law:
     * FREE ≈ 25-35% of the card's total points.
     * Spec 32 v4 — enchant/disenchant carry NO authored `free` rider: their FREE
     * line is engine-derived (a timed instance of the same hooked passive), so this
     * field stays undefined for them.
     */
    free?: CardRider;
    /**
     * Spec 32 v4 — a one-line mechanical summary of an enchant/disenchant's
     * HOOKED passive (the effect lives in the engine, not in `combatEffects`, so
     * it is otherwise invisible to the catalog and the card UI). Rendered on both
     * lines: FREE grants it for a few rounds (timed), PAID makes it permanent —
     * same effect, only the duration differs. Required for enchant/disenchant;
     * ignored for spells.
     */
    persistentEffect?: string;
    combatEffects?: CardCombatEffects[];
    specialMechanics?: CardSpecialMechanic[];
    /**
     * Phase 66 — Tier 2 synergy clause. When present, the card engine
     * evaluates the synergy after `calculateCardDamage` and before
     * applying `combatEffects` / `specialMechanics`. See {@link CardSynergy}.
     */
    synergy?: CardSynergy;
    /**
     * Phase 91 — Optional friendship counter increment. When present, executeCard
     * increments the combat friendship counter by this amount after damage/effects
     * but before resource costs. Does not require defend stance.
     */
    incrementsFriendship?: number;
    /**
     * Content-provenance metadata used by the tuning `--focus` filter
     * (`src/Tuning/focus.parser.ts`). `addedIn` is an ISO date / phase tag;
     * `tags` are freeform labels (e.g. `'mid-game'`, `'damage'`). Both
     * optional and ignored by the card engine.
     */
    addedIn?: string;
    tags?: string[];
    // ── Fate Engine P1 (spec 31 §4.1) — per-card die-interaction lines. Design
    //    law: every Tier-2+ card carries exactly ONE of threshold / dieBonus /
    //    fate / die-manipulation / react; Tier-1 at most one. All combat-engine
    //    owned; the card engine ignores them. ───────────────────────────────────
    /**
     * RESONANCE THRESHOLD (Spirit Island element thresholds): when the
     * encounter's spent-die tally of `color` is ≥ `count` at play time, the
     * rider fires automatically, free. One spend, two payoffs.
     */
    threshold?: { color: StatType; count: number; rider: CardRider };
    /**
     * DIE BONUS: the rider fires when the POWERING die's color matches —
     * `'match'` = this card's own stance (or Wild), a named color = exactly
     * that color, `'off'` = any color that is NOT this card's stance (the
     * straw-man line: the wrong target, hit harder).
     */
    dieBonus?: { onColor: StatType | 'match' | 'off'; rider: CardRider };
    /**
     * FATE (Mage Knight no-dead-faces): this card may be POWERED BY AN X DIE.
     * A colored/wild die plays the card normally; the X die fires the printed
     * `rider` on top and costs `recoilHp` (the impossible made load-bearing).
     */
    fate?: { rider: CardRider; recoilHp?: number };
    /**
     * Spec 32 v3 T4 — FALLEN theme-state condition line: the rider fires free
     * when the player is Fallen (carries ≥2 distinct self-debuffs) at play time.
     */
    fallen?: { rider: CardRider };
}
