/**
 * Skills System Types
 * Skills come in two categories: fallacies and paradoxes, and run on a five-
 * resource resonance economy (heart / body / mind / fallacy / paradox). See
 * `specs/04-skills-engine.md` for the full economy design.
 */

import type { AlignmentGate } from '../NPCs/types';

/**
 * Philosophical aspect alignment for skills
 * Determines which base stat the skill scales with and which combat type it uses.
 * - 'body': Physical/strength-based skills
 * - 'mind': Mental/intelligence-based skills
 * - 'heart': Emotional/charisma-based skills
 */
export type StatType = 'body' | 'mind' | 'heart';

/**
 * Card category type
 * - 'fallacy': Skills based on logical fallacies (generate ⚖ on use)
 * - 'paradox': Skills based on philosophical paradoxes (generate ∞ on use)
 */
export type CardCategory = 'fallacy' | 'paradox';

/**
 * Tier of a skill — mirrors the effect tier system. Drives the resist tier
 * used when a skill applies a `combatEffects` payload through the Spec 03
 * machinery (Tier 1 auto-applies, Tier 2 resisted, Tier 3 only nat-20 repels).
 */
export type CardTier = 1 | 2 | 3;

/**
 * Targeting scope for a skill effect.
 * - `'self'`  — the caster.
 * - `'enemy'` — the current opponent.
 * Multi-combatant targeting is deferred to Spec 07.
 */
export type CardTarget = 'self' | 'enemy';

/**
 * Per-combat player resource counters live on `CombatState`. Seeded at combat
 * start from item/set grants, generated by player basic actions (heart/body/mind
 * from stance attacks/defends), and by player skill use (fallacy/paradox from
 * skill category/tier). Character carries `knownSkills` as the combat catalogue
 * (ADR-0002 / Phase 99 \u2014 there is no equipped-skill loadout gate).
 * `knownSkills` is not a persistent mana/resource pool.
 */
export interface CombatResources {
    heart: number;
    body: number;
    mind: number;
    fallacy: number;
    paradox: number;
}

/**
 * Learning requirement for a skill
 * Defines the prerequisites a character must meet to learn this skill.
 * Moral-alignment gates (Spec 10) are deferred.
 *
 * @property level - Minimum character level required to learn this skill
 * @property statRequirementType - Optional: which base stat must meet the requirement (body/mind/heart)
 * @property statRequirementValue - Optional: minimum value for the specified stat
 * @property prerequisiteSkill - Optional: skill that must be learned before this skill can be learned
 */
export interface CardLearningRequirement {
    level: number;
    statRequirementType?: StatType;
    statRequirementValue?: number;
    prerequisiteSkill?: string;
    /**
     * Phase 46 — alignment gate. Locks the skill behind a position on the
     * Phase 42 alignment cube. Single-clause gate (axis + op + value);
     * missing alignment on the character implicitly fails the gate.
     */
    requiresAlignment?: AlignmentGate;
}

/**
 * Combat effect payload applied by a skill. Routes through
 * `resolveEffectApplication` (Spec 03) so resist / repel / crit follow the
 * same rules as proc-applied effects.
 *
 * @property effectId    - ID of the effect in the global effects library.
 * @property appliedTo   - 'self' or 'opponent' (relative to the caster).
 * @property description - Display text for the CLI / UI.
 * @property intensity   - Optional initial intensity override (default 1).
 *                         Used by skills like Liar's Echo that stack a Tier 1
 *                         mark with extra intensity on first application.
 * @property duration    - Optional remaining-duration override (defaults to
 *                         the effect's library duration). Switches the apply
 *                         path into `additive` duration mode so the override
 *                         survives stacking.
 */
export interface CardCombatEffects {
    effectId: string;
    appliedTo: 'self' | 'opponent';
    description?: string;
    intensity?: number;
    duration?: number;
}

/**
 * Bespoke skill mechanics that don't map cleanly onto an ActiveEffect
 * payload. Each is processed by `executeSkill` after damage and after
 * `combatEffects`. Kept as a discriminated union so the resolver / UI can
 * branch on `kind` without runtime tag parsing.
 *
 * - `strip_random_buff`: remove one random buff from the target. Used by
 *   Ad Hominem Strike (enemy) and similar harassment effects.
 * - `convert_enemy_buff_to_self`: strip a random buff from the enemy and
 *   apply the same effect to the player. Ship of Theseus.
 * - `secondary_heal_self`: heal the player for
 *   `baseStats[stat] × SKILL_STAT_MULTIPLIER × (multiplier ?? 1)` after the
 *   primary damage resolves. Used by Mob Appeal to bolt a small self-heal
 *   onto an enemy-targeted strike.
 * - `befriend_attempt`: Phase 108 - attempt to befriend the enemy, opening
 *   a mercy choice state if successful (requires HP gate eligibility).
 */
export type CardSpecialMechanic =
    | { kind: 'strip_random_buff'; appliedTo: 'self' | 'enemy' }
    | { kind: 'convert_enemy_buff_to_self' }
    | { kind: 'secondary_heal_self'; stat: StatType; multiplier?: number }
    | { kind: 'befriend_attempt' }
    /** Hazard-Pattern Combat — grants the player GUARD (a shield that absorbs the
     *  enemy's next telegraphed threat). Handled by the combat engine, not the
     *  skill engine. `amount` is the base Guard before read/free scaling. */
    | { kind: 'guard'; amount: number }
    /** RUPTURE — consume ALL DoT on the foe and deal their remaining total as a
     *  burst (read + vulnerable scaled, capped at `RUPTURE_BURST_CAP`). `bonusPct`
     *  is an extra flat fraction on the detonation. HP behavior owned by the
     *  combat engine (mirrors `guard`); the skill engine no-ops it. */
    | { kind: 'rupture'; bonusPct?: number }
    /** COMPOUND — deal `perDebuff` HP per DISTINCT debuff on the foe (counted
     *  before this card's own debuff lands, capped at `COMPOUND_COUNT_CAP`,
     *  read + vulnerable scaled). HP behavior owned by the combat engine. */
    | { kind: 'compound'; perDebuff: number }
    /** SIPHON — heal the player for `pct` of the HP this card erodes from the
     *  foe (strike + any rupture/compound/execute burst). Combat-engine owned. */
    | { kind: 'siphon'; pct: number }
    /** BARRIER — add `amount` (read-scaled) to the player's STACKING, persistent
     *  damage soak (`CombatEncounterState.barrier`), distinct from one-shot GUARD.
     *  Combat-engine owned. */
    | { kind: 'barrier'; amount: number }
    /** RIPOSTE — a one-shot parry: reduce the foe's next telegraphed hit by
     *  `reduce` and counter for `damage` (read-scaled). Combat-engine owned. */
    | { kind: 'riposte'; damage: number; reduce: number }
    /** EXECUTE — a finisher: when the foe is at/below `hpPct` of max HP OR carries
     *  at least `dotStacks` distinct DoT effects, deal a large (typically lethal)
     *  hit with optional `recoilPct` self-damage; otherwise fall back to the
     *  normal small strike. Combat-engine owned. */
    | { kind: 'execute'; hpPct: number; dotStacks: number; recoilPct?: number }
    /** AMPLIFY — read the foe's pending DoT total (getPendingDotTotal) ×
     *  `multiplier` and fire as a one-time HP burst. DoT effects are NOT consumed —
     *  they keep ticking (distinct from RUPTURE which consumes them). Capped at
     *  AMPLIFY_BURST_CAP. Combat-engine owned; skill engine no-ops it. */
    | { kind: 'amplify'; multiplier: number }
    /** GRANT_PERMANENT_WILD_DIE — Master Spec §4. Adds `wildCount` Wild dice and
     *  `deadCount` locked X dice to `CombatEncounterState.permanentWildDice` /
     *  `permanentDeadDice` for the REST of the encounter (deck-building-style
     *  escalation, not a one-turn trick), clamped to `MAX_PERMANENT_WILD_DICE`.
     *  Only ever fired from a card's SURGE (die-powered) action — the doctrine is
     *  weak plays never touch the pool. Combat-engine owned; skill engine no-ops
     *  it, mirroring `guard`/`barrier`/`rupture`. */
    | { kind: 'grant_permanent_wild_die'; wildCount: number; deadCount: number }
    // ── Fate Engine P1 (spec 31 §4.1) — die-manipulation verbs, all combat-engine
    //    owned (the skill engine no-ops them, mirroring guard/rupture). ──────────
    /** REROLL_SPENT — re-roll every spent/blocked die in the tray (the library
     *  sibling of the Press Fate signature). */
    | { kind: 'reroll_spent' }
    /** REFRESH_DIE — the powering die returns to `available` after this play
     *  (independent of the variety-chain rule). */
    | { kind: 'refresh_die' }
    /** CONVERT_DIE_COLOR — the powering die returns REFRESHED as a WILD die
     *  ("still your die?" — maximally flexible, deterministic, no color picker). */
    | { kind: 'convert_die_color' }
    /** CREATE_TEMPORARY_DIE — forge a fresh die of `color` (temporary: true).
     *  It joins the RESERVE at 0 pips when a slot is free; otherwise it burns
     *  for +1 Conviction. */
    | { kind: 'create_temporary_die'; color: 'heart' | 'body' | 'mind' | 'wild' }
    /** GRANT_PIP — every die currently in the Reserve ripens +`count` pips
     *  (clamped to the pip cap). */
    | { kind: 'grant_pip'; count: number }
    /** BANK_SPENT_DIE — instead of being spent, the powering die goes to the
     *  Reserve at 0 pips (if a slot is free; otherwise it is spent normally). */
    | { kind: 'bank_spent_die' }
    /** REACT — if the foe carries BOTH status `a` and status `b` at
     *  `minIntensity`+, CONSUME them and detonate: burst = `burstPerIntensity` ×
     *  (consumed intensities), on the mechanic-damage path (never strike-weighted),
     *  plus an optional `product` status. A fired REACT refreshes the drafted die
     *  (the crescendo keeps the turn alive). */
    | { kind: 'react'; a: string; b: string; minIntensity: number;
        burstPerIntensity: number;
        product?: { effectId: string; intensity: number; duration: number } };

/**
 * Fate Engine P1 — a card RIDER: a bundle of real-unit bonuses fired by a
 * die-interaction line (`threshold` / `dieBonus` / `fate`). Every field is an
 * exact engine unit so generated action text is the applied number (P0-truth
 * law). All fields optional; absent = 0/false.
 */
export interface CardRider {
    /** +N intensity on the statuses THIS play lands on the enemy. */
    bonusIntensity?: number;
    /** +N turns on the statuses THIS play lands on the enemy. */
    bonusDuration?: number;
    /** Immediate flat HP chip to the enemy (mechanic-damage path, unweighted). */
    chipHp?: number;
    /** +N Guard. */
    guard?: number;
    /** +N Conviction (clamped to the cap). */
    conviction?: number;
    /** Refresh the powering die back to available. */
    refreshDie?: boolean;
    /** Reveal the NEXT threat phase's hidden stance. */
    revealStance?: boolean;
    /** Immediately tick every enemy DoT once (extra tick — durations untouched). */
    tickAllDots?: boolean;
    /** Cleanse up to N of the player's own debuffs (tier-3 scope). */
    cleanse?: number;
    /** Heal the player N HP. */
    healHp?: number;
    /** Draw N cards. */
    drawCards?: number;
}

/**
 * Phase 66 — synergy predicate. The matched ActiveEffect on `on`
 * satisfies the predicate when its `effectId` matches AND its
 * `intensity` >= `intensityMin` (if set) AND its `remainingDuration`
 * >= `durationMin` (if set).
 */
export interface SynergyPredicate {
    effectId: string;
    on: 'caster' | 'target';
    intensityMin?: number;
    durationMin?: number;
}

/**
 * Phase 66 — Tier 2 synergy clause. Optional payload on `Card` that
 * rewards stance-switching by conditioning damage / effect application
 * on the presence of an ActiveEffect already on the field (or, for
 * Resonance Detonation, on the unconditional cast).
 *
 * Synergy damage (added to the skill's base damage; doesn't replace):
 * ```
 * synergyDamage = bonusDamage
 *               + matched.intensity            × intensityDamageMul
 *               + matched.remainingDuration    × durationDamageMul
 *               + consumedTokens               × resourceTokenDamageMul
 * ```
 *
 * Side effects (in resolution order):
 *   1. `consumeAllResources` zeros the caster's `combatResources` pool
 *      and captures `consumedTokens = body + mind + heart` for the
 *      damage formula.
 *   2. Synergy damage applies to the target.
 *   3. `consumeMatched` clears the matched ActiveEffect on the
 *      predicate's `on` side.
 *   4. `clearAllEffectsBothSides` clears all ActiveEffects on both
 *      combatants (Phase 60 set-bonus passives included — design
 *      intent per Phase 66 D9).
 *   5. `applyEffectOnFire` applies a fresh effect (typically used to
 *      "swap type" — body Thorns → heart Bat-Swarm-Thoughtform).
 *
 * Synergy runs in `executeSkill` AFTER `calculateSkillDamage` but
 * BEFORE the skill's own `combatEffects` apply, so consumed effects
 * don't get post-fire effects layered on top.
 */
export interface CardSynergy {
    /** Optional predicate. If absent, the synergy fires unconditionally
     *  when the skill is cast (used by Resonance Detonation per D6). */
    predicate?: SynergyPredicate;
    /** Flat bonus damage on match. */
    bonusDamage?: number;
    /** Multiplier × matched effect's `remainingDuration`. */
    durationDamageMul?: number;
    /** Multiplier × matched effect's `intensity`. */
    intensityDamageMul?: number;
    /** Multiplier × total consumed combat-resource tokens (only fires
     *  when `consumeAllResources` is true). */
    resourceTokenDamageMul?: number;
    /** Clear the matched effect from the predicate's `on` side. */
    consumeMatched?: boolean;
    /** Zero the caster's full `combatResources` pool. */
    consumeAllResources?: boolean;
    /** Clear all ActiveEffects from both combatants. */
    clearAllEffectsBothSides?: boolean;
    /** Apply an additional effect on the caster when synergy fires. */
    applyEffectOnFire?: CardCombatEffects;
}

/**
 * Card entity — an ability that can be learned/unlocked and used in combat.
 *
 * @property id              - Unique identifier for this skill.
 * @property name            - Display name.
 * @property description     - Flavor text or lore.
 * @property category        - Fallacy or paradox (drives the philosophical
 *                             token generated on use).
 * @property philosophicalAspect - Stat alignment of the skill (heart/body/mind).
 * @property tier            - 1 / 2 / 3, mirrors the effect tier system.
 * @property targetType      - 'self' or 'enemy'.
 * @property basePower       - Flat damage / heal magnitude before stat scaling.
 * @property scalingStat     - Base stat the skill scales off of (typically
 *                             matches `philosophicalAspect`, but may deviate).
 * @property scalingMultiplier - Optional multiplier on the scaling-stat term
 *                               (default 1). Card damage / heal becomes
 *                               `basePower + stat × SKILL_STAT_MULTIPLIER × scalingMultiplier`.
 *                               Used by self-heals like Appeal to Pity that want
 *                               a more substantial restorative effect.
 * @property combatEffects   - Optional list of effect payloads to apply.
 * @property specialMechanics - Optional bespoke behaviours (buff-strip,
 *                              buff-conversion, secondary heal, etc.). Resolved
 *                              after damage and after `combatEffects`.
 * @property learningRequirement - Optional prerequisites needed to learn.
 */
export interface Card {
    id: string;
    name: string;
    category: CardCategory;
    philosophicalAspect: StatType;
    description: string;
    tier: CardTier;
    targetType: CardTarget;
    basePower: number;
    scalingStat: StatType;
    scalingMultiplier?: number;
    combatEffects?: CardCombatEffects[];
    specialMechanics?: CardSpecialMechanic[];
    learningRequirement?: CardLearningRequirement;
    /**
     * Phase 66 — Tier 2 synergy clause. When present, the skill engine
     * evaluates the synergy after `calculateSkillDamage` and before
     * applying `combatEffects` / `specialMechanics`. See {@link CardSynergy}.
     */
    synergy?: CardSynergy;
    /**
     * Phase 91 — Optional friendship counter increment. When present, executeSkill
     * increments the combat friendship counter by this amount after damage/effects
     * but before resource costs. Does not require defend stance.
     */
    incrementsFriendship?: number;
    /**
     * Content-provenance metadata used by the tuning `--focus` filter
     * (`src/Tuning/focus.parser.ts`). `addedIn` is an ISO date / phase tag;
     * `tags` are freeform labels (e.g. `'mid-game'`, `'damage'`). Both
     * optional and ignored by the skill engine.
     */
    addedIn?: string;
    tags?: string[];
    // ── Fate Engine P1 (spec 31 §4.1) — per-card die-interaction lines. Design
    //    law: every Tier-2+ card carries exactly ONE of threshold / dieBonus /
    //    fate / die-manipulation / react; Tier-1 at most one. All combat-engine
    //    owned; the skill engine ignores them. ───────────────────────────────────
    /**
     * RESONANCE THRESHOLD (Spirit Island element thresholds): when the
     * encounter's spent-die tally of `color` is ≥ `count` at play time, the
     * rider fires automatically, free. One spend, two payoffs.
     */
    threshold?: { color: StatType; count: number; rider: CardRider };
    /**
     * DIE BONUS: the rider fires when the POWERING die's color matches —
     * `'match'` = this card's own stance (or Wild), a named color = exactly
     * that color, `'off'` = any color that is NOT this card's stance (the
     * straw-man line: the wrong target, hit harder).
     */
    dieBonus?: { onColor: StatType | 'match' | 'off'; rider: CardRider };
    /**
     * FATE (Mage Knight no-dead-faces): this card may be POWERED BY AN X DIE.
     * A colored/wild die plays the card normally; the X die fires the printed
     * `rider` on top and costs `recoilHp` (the impossible made load-bearing).
     */
    fate?: { rider: CardRider; recoilHp?: number };
}
