/**
 * Game Mechanics Constants
 * Single source of truth for all numeric values that control game rules.
 * Import from here instead of hardcoding magic numbers across the codebase.
 */

// ============================================================================
// CHARACTER — RESOURCE CALCULATIONS
// ============================================================================
// The player's VITAE pool.
// Formula: VITAE = PLAYER_VITAE_BASE + 12·body + 6·mind + 6·heart (body is
// the hardy stat; 170 at 5/5/5).
// The flat base keeps a level-1 pilgrim alive long enough to see a second
// telegraph when enemy threats open in the high single digits; the
// per-stat term is what progression buys. Level influences VITAE through the
// authored stat budget, not by a second multiplicative level factor.
// Reference points: level 1 ≈ 100, level 3 ≈ 120, level 18 ≈ 350.

export const RESOURCE_MULTIPLIERS = {
    VITAE_PER_BODY: 12,
    VITAE_PER_MIND: 6,
    VITAE_PER_HEART: 6,
} as const;

/** Flat floor added to every player VITAE pool before the per-stat term. */
export const PLAYER_VITAE_BASE = 50;

// ============================================================================
// PROGRESSION — EXPERIENCE & LEVELING
// ============================================================================

// Reaching level L+1 costs L × EXPERIENCE_STEP more XP
// (`Character/experience.ts`). A full Act 1 clear ends at level 5.
export const EXPERIENCE_STEP = 250;

// Stat points granted per level promotion. Spent via
// `allocateStatPoint` to raise heart / body / mind. There is
// no level cap, so the points stream is uncapped — content authors
// decide where progression naturally stops.
export const STAT_POINTS_PER_LEVEL = 3;

// ============================================================================
// EFFECTS — STACKING CAPS
// ============================================================================
// Hard ceiling on how high any single effect's intensity or remaining duration
// can grow, regardless of stacking mode or repeated applications.

// The intensity ceiling sits above every printed amount (cards print THORNS
// 12-20 and DOOM 12), so no printed number is silently clipped. The DURATION
// cap is 10: a 10-turn calendar is a long time.
export const MAX_EFFECT_INTENSITY = 30;
export const MAX_EFFECT_DURATION  = 10;

// ============================================================================
// CARDS — SCALING & RESOURCE GENERATION

/** Tokens generated by basic actions, keyed by outcome. */
export const RESOURCE_GENERATION = {
    ATTACK_HIT:  3,
    ATTACK_MISS: 1,
    DEFEND:      5,
} as const;

// Probability that an enemy answers a player's HOSTILE card with a card of
// its own ("answer power with power"). Distinct from the lead-with-card
// cadence (`ENEMY_CARD_PICK_CHANCE`): this dial governs the REACTIVE answer
// to the player's offensive card, not the enemy's own opening. Set at 0.10 —
// a felt but not overwhelming reactive threat; a deliberate floor and a
// tuning candidate.
export const ENEMY_CARD_ANSWER_CHANCE = 0.10;

// Effects-driven resolution thresholds
// Combined intensity of control/debuff effects needed to force saturation yield (friendship route)
export const EFFECTS_RESOLUTION_DEBUFF_INTENSITY_THRESHOLD = 3;
// Minimum DoT damage per round needed to force erosion victory route
export const EFFECTS_RESOLUTION_DOT_DAMAGE_THRESHOLD = 2;
// Horizon (in rounds) for the DoT-erosion victory route: DoT forces an early
// victory only if it could finish the enemy within this many rounds. This is
// the conservative gate that decides whether sustained status damage "clearly
// closes the fight" — NOT the combat timeout (that is the ~80-round cap in the
// playtest/combat loop). On high-HP enemies the default 10 is unreachable
// (rounds-to-kill scales with HP), which is why lowering the damage threshold
// alone never resolved L30+ timeouts; raising this horizon lets a strong DoT
// resolve a fight it will demonstrably win before the cap. Tuned by the loop.
export const EFFECTS_RESOLUTION_DOT_MAX_ROUNDS_TO_KILL = 10;

// ============================================================================
// ENEMY — STAT BUDGET PER LEVEL
// ============================================================================
// Total base-stat budget granted to an enemy is `level × ENEMY_STAT_PER_LEVEL`,
// distributed across heart / body / mind. Players, by contrast, carry a
// `level × 5` budget, so the default `3` makes a same-level enemy roughly 60%
// of a player's raw stat weight — a starting point the tuning workflow A/B's.
//
// This is the single tunable knob for global enemy power scaling. Authored
// enemies that opt into budget-based stats build their `baseStats` via
// `enemyStatBudget(level)` (see `src/Enemy/index.ts`); enemies that
// hand-author `baseStats` are unaffected.
export const ENEMY_STAT_PER_LEVEL = 3;

// Off-budget "gear tier" scaling term to counteract player power accumulation.
// Represents the compounding advantage players gain from equipment upgrades and
// card library expansion that enemies lack. Applied as a multiplicative bonus
// to enemy defensive stats (HP/defense/resists), weighted away from attack to
// avoid defeat spikes. The curve is ≈0 at level 1 (early game untouched) and
// grows with level to balance late-game trivialization. Magnitude is tuned by
// the mechanics loop via the tunable registry.
export const ENEMY_GEAR_TIER_PER_LEVEL = 0.02;

// ============================================================================
// ENEMY — VITAE
// ============================================================================
// Enemy VITAE does not ride the player's per-stat formula. `baseStats` still
// drives stance procs, derived combat stats and befriend logic; the pool a
// player has to chew through is its own authored/derived number, so difficulty
// bands separate cleanly and a boss can be a wall without a grotesque stat
// budget.
//
//   vitae = round((ENEMY_VITAE_BASE + ENEMY_VITAE_PER_LEVEL × level)
//                 × ENEMY_VITAE_MULT[difficulty])
//
// An enemy may author `vitae` directly on `createEnemy` to override the curve
// (every boss and unique does). Reference points off the curve: L1 normal ≈
// 38, L7 elite ≈ 120, L6 boss ≈ 148, L13 normal ≈ 134, L18 boss ≈ 331.
export const ENEMY_VITAE_BASE = 30;
// A player's damage per turn is set by CARD RANK and does not grow with
// level, so a steep per-level pool outruns any deck by the late campaign.
// At 8/level the curve stays ahead of card growth without
// leaving it behind.
export const ENEMY_VITAE_PER_LEVEL = 8;

export const ENEMY_VITAE_MULT = {
    simple: 0.6,
    normal: 1.0,
    elite:  1.4,
    boss:   1.9,
    unique: 2.4,
} as const;
