/**
 * Game Mechanics Constants
 * Single source of truth for all numeric values that control game rules.
 * Import from here instead of hardcoding magic numbers across the codebase.
 */

// ============================================================================
// CHARACTER — STAT DERIVATION MULTIPLIERS
// ============================================================================
// Applied to each base stat (body / mind / heart) to produce the four
// derived combat stats for that attribute category.

export const STAT_MULTIPLIERS = {
    ATTACK:  1,   // physicalAttack / mentalAttack / emotionalAttack — combat rolls
    DEFENSE: 3,
    SAVE:    2,
    TEST:    4,
} as const;

// ============================================================================
// CHARACTER — RESOURCE CALCULATIONS
// ============================================================================
// THE BIG NUMBERS REWRITE (2026-09-02) — the player's VITAE pool.
// Formula: VITAE = PLAYER_VITAE_BASE + (body + heart + mind) × HEALTH_PER_STAT.
// The flat base keeps a level-1 pilgrim alive long enough to see a second
// telegraph now that enemy threats open in the high single digits; the
// per-stat term is what progression buys. Level influences VITAE through the
// authored stat budget, not by a second multiplicative level factor.
// Reference points: level 1 ≈ 100, level 3 ≈ 120, level 18 ≈ 350.

export const RESOURCE_MULTIPLIERS = {
    HEALTH_PER_STAT: 8,
} as const;

/** Flat floor added to every player VITAE pool before the per-stat term. */
export const PLAYER_VITAE_BASE = 50;

// ============================================================================
// PROGRESSION — EXPERIENCE & LEVELING
// ============================================================================

export const EXPERIENCE_PER_LEVEL = 1000;

// Stat points granted per level promotion (Spec 06 Q3). Spent via
// `allocateStatPoint` to raise heart / body / mind. Per Spec 06 Q5 there is
// no level cap today, so the points stream is uncapped — content authors
// decide where progression naturally stops.
export const STAT_POINTS_PER_LEVEL = 3;

// ============================================================================
// COMBAT — DEFENSE MULTIPLIERS
// ============================================================================
// Applied to a combatant's base defense stat when they choose the 'defend'
// action.  The multiplier is selected based on the defender's type-advantage
// relative to the attacker (heart > body > mind > heart).
//
//   Defending with ADVANTAGE    → 2× defense  (picked the right counter-type)
//   Defending with NEUTRAL      → 1.5× defense (same type, no bonus)
//   Defending with DISADVANTAGE → 1× defense  (picked the wrong type, weaker)
//
// Keys deliberately match the Advantage union type so they can be used as
// a direct lookup: DEFENSE_MULTIPLIERS[advantage].

export const DEFENSE_MULTIPLIERS: Record<'advantage' | 'neutral' | 'disadvantage', number> = {
    advantage:    2,
    neutral:      1.5,
    disadvantage: 1.0,
} as const;

// Applied when a combatant did NOT choose the 'defend' action (i.e. they are
// taking damage after losing an attack contest with no active defense bonus).
export const PASSIVE_DEFENSE_MULTIPLIER = 1;

// ============================================================================
// EFFECTS — STACKING CAPS
// ============================================================================
// Hard ceiling on how high any single effect's intensity or remaining duration
// can grow, regardless of stacking mode or repeated applications.

// THE BIG NUMBERS REWRITE (2026-09-02) — the intensity ceiling was 10, set
// when POISON 1-4 was a big number. At the new scale six cards print THORNS
// 12-20 and DOOM 12 and every one of them silently landed 10 — a printed
// number the engine did not apply, which is the one text law the repeal kept.
// The DURATION cap is untouched: a 10-turn calendar is still a long time, and
// stretching it is a different design question.
export const MAX_EFFECT_INTENSITY = 30;
export const MAX_EFFECT_DURATION  = 10;

// Spec 32 v4 §2.1 — the FREE (dieless) enchant/disenchant line grants a TIMED
// instance of the card's passive that stays active this many combat rounds before
// it ticks out. The PAID line makes the same passive permanent (rest of combat).
export const FREE_ENCHANT_ROUNDS = 3;

// ============================================================================
// CARDS — SCALING & RESOURCE GENERATION

/** Tokens generated by basic actions, keyed by outcome. */
export const RESOURCE_GENERATION = {
    ATTACK_HIT:  3,
    ATTACK_MISS: 1,
    DEFEND:      5,
} as const;

// ============================================================================
// COMBAT — RESOURCE CARRY (between encounters)
// ============================================================================
// A fraction of UNSPENT philosophical resources (fallacy / paradox — the card
// fuel) carries from a won combat into the next combat's seed. This rewards
// casting cards (which apply status effects) and planning across encounters —
// the STRATEGIST path the VISION.md doctrine optimises for. Stance tokens
// (heart/body/mind) are NOT carried, so turtling or basic-attack token-banking
// earns no cross-combat momentum. Conservative defaults; the tuning loop owns
// the numbers.
export const RESOURCE_CARRY = {
    /** Fraction of unspent fallacy / paradox carried forward (floored). */
    FRACTION: 0.5,
    /** Hard cap on the amount carried per resource, so carry cannot snowball. */
    CAP: 3,
} as const;

// ============================================================================
// COMBAT — FRIENDSHIP MECHANIC
// ============================================================================
// When both combatants choose 'defend' on the same turn the friendship
// counter increments.  Reaching the maximum ends combat peacefully.

export const FRIENDSHIP_COUNTER_MAX = 3;

// Phase 150 — probability that an enemy answers a player's HOSTILE card with
// a card of its own ("answer power with power"). Distinct from the Phase 49
// lead-with-card cadence (`ENEMY_CARD_PICK_CHANCE`): this dial governs the
// REACTIVE answer to the player's offensive card, not the enemy's own opening.
// Set at 0.10 — a felt but not overwhelming reactive threat. A guaranteed
// (1.0) answer crushes both the STRATEGIST friendship route and the difficult
// lethal anchor (`mirac`); an answer-chance sweep on the Phase 121
// difficult anchor found win rate 0.04 at 0.20–0.35, 0.12 at 0.15, and 0.16 at
// 0.10 against an authored band of 0.10–0.40, while the normal anchor (0.80)
// and difficult-anchor friendship rate (0.20) stay flat across the range. 0.10
// keeps the doctrine ("answer power with power") alive with safe band margin;
// it is a deliberate floor, flagged as a tuning candidate to raise once the
// difficult anchor's stat block is retuned. Recorded in
// automation/playtest/BALANCE_LEDGER.md (marker M-150).
export const ENEMY_CARD_ANSWER_CHANCE = 0.10;

// Phase 125 — Effects-driven resolution thresholds
// Combined intensity of control/debuff effects needed to force saturation yield (friendship route)
export const EFFECTS_RESOLUTION_DEBUFF_INTENSITY_THRESHOLD = 3;
// Minimum DoT damage per round needed to force erosion victory route
export const EFFECTS_RESOLUTION_DOT_DAMAGE_THRESHOLD = 2;
// Horizon (in rounds) for the DoT-erosion victory route: DoT forces an early
// victory only if it could finish the enemy within this many rounds. This is
// the conservative gate that decides whether sustained status damage "clearly
// closes the fight" — NOT the combat timeout (that is the ~80-round cap in the
// playtest/combat loop). On high-HP enemies the default 10 is unreachable
// (rounds-to-kill scales with HP), which is why lowering the damage threshold
// alone never resolved L30+ timeouts; raising this horizon lets a strong DoT
// resolve a fight it will demonstrably win before the cap. Tuned by the loop.
export const EFFECTS_RESOLUTION_DOT_MAX_ROUNDS_TO_KILL = 10;

// Base intensity granted per proc-applied status effect when the trigger does
// not override it. Control effects stack by DURATION (their intensity stays at
// this base), so the saturation-yield route's combined-intensity threshold is
// only reachable when several control effects are active OR this base is raised.
// Symmetric (applies to whoever procs the effect), so the defeat-regression
// guard bounds it; engagement-positive (more decisive status). Tuned by the loop.
export const EFFECT_BASE_PROC_INTENSITY = 2; // Phase 130 — raised from 1 for l15 STRATEGIST targeting

// ============================================================================
// ENEMY — STAT BUDGET PER LEVEL
// ============================================================================
// Total base-stat budget granted to an enemy is `level × ENEMY_STAT_PER_LEVEL`,
// distributed across heart / body / mind. Players, by contrast, carry a
// `level × 5` budget, so the default `3` makes a same-level enemy roughly 60%
// of a player's raw stat weight — a starting point the tuning workflow A/B's.
//
// This is the single tunable knob for global enemy power scaling. Authored
// enemies that opt into budget-based stats build their `baseStats` via
// `enemyStatBudget(level)` (see `src/Enemy/index.ts`); legacy enemies that
// hand-author `baseStats` are unaffected.
export const ENEMY_STAT_PER_LEVEL = 3;

// Off-budget "gear tier" scaling term to counteract player power accumulation.
// Represents the compounding advantage players gain from equipment upgrades and
// card library expansion that enemies lack. Applied as a multiplicative bonus
// to enemy defensive stats (HP/defense/resists), weighted away from attack to
// avoid defeat spikes. The curve is ≈0 at level 1 (early game untouched) and
// grows with level to balance late-game trivialization. Magnitude is tuned by
// the mechanics loop via the tunable registry.
export const ENEMY_GEAR_TIER_PER_LEVEL = 0.02;

// ============================================================================
// ENEMY — VITAE (THE BIG NUMBERS REWRITE, 2026-09-02)
// ============================================================================
// Enemy VITAE no longer rides the player's per-stat formula. `baseStats` still
// drives stance procs, derived combat stats and befriend logic; the pool a
// player has to chew through is its own authored/derived number, so difficulty
// bands separate cleanly and a boss can be a wall without a grotesque stat
// budget.
//
//   vitae = round((ENEMY_VITAE_BASE + ENEMY_VITAE_PER_LEVEL × level)
//                 × ENEMY_VITAE_MULT[difficulty])
//
// An enemy may author `vitae` directly on `createEnemy` to override the curve
// (every boss and unique does). Reference points off the curve: L1 normal ≈
// 38, L7 elite ≈ 120, L6 boss ≈ 148, L13 normal ≈ 134, L18 boss ≈ 331.
export const ENEMY_VITAE_BASE = 30;
// Measured against the playtest matrix 2026-09-02 and pulled back from 18: a
// player's damage per turn is set by CARD RANK and does not grow with level,
// so a pool growing at 18/level outran any deck by the late campaign (every
// late cell read 0%). At 8/level the curve stays ahead of card growth without
// leaving it behind.
export const ENEMY_VITAE_PER_LEVEL = 8;

export const ENEMY_VITAE_MULT = {
    simple: 0.6,
    normal: 1.0,
    elite:  1.4,
    boss:   1.9,
    unique: 2.4,
} as const;
