import { WorldState, QuestLog, Encounter } from '../World/types';
import { LabyrinthProgress } from '../World/Labyrinth/types';
import { Character } from '../Character/types';

/**
 * Top-level game state. The root object that aggregates the player,
 * the world, the staged encounter, the quest log, and world flags.
 *
 * @property version          - Schema version, incremented on breaking changes
 *                              so save files can be migrated.
 * @property currentEncounter - The full encounter the player is
 *                              fighting. Carries multi-enemy info plus the
 *                              origin tag so `END_COMBAT` can roll loot and
 *                              advance kill objectives. Combat itself is driven
 *                              by the Hazard-Pattern engine outside the store;
 *                              `START_COMBAT` only stages this encounter and
 *                              `END_COMBAT` consumes it to grant rewards.
 *                              Transient: excluded from persisted saves
 *                              (encounters re-roll on load).
 * @property quests           - Player's quest log (per-objective tracking).
 * @property flags            - Generic world flags set by dialogue / events.
 *                              Used by dialogue `requires.flag` gates and by
 *                              quest objectives of type `'flag'`.
 * @property rngState         - Current RNG seed state for deterministic replays.
 *                              Persisted and restored to maintain reproducible
 *                              random sequences across save/load cycles.
 */
/**
 * Per-foe codex / journal entry unlocked when the player
 * befriends an enemy (`outcome === 'friendship'`). The engine
 * auto-appends `journalEntry.id` to `state.codex.unlockedEntries`
 * (de-duped) and surfaces `{ id, title }` on
 * `CombatEndReport.friendshipReward.codexEntryUnlocked`; the consumer
 * (mobile Codex tab, future CLI surface) looks up the entry body via
 * the source `Enemy` (or a future `CodexLibrary` registry).
 *
 * Semantically a Game-loop type (paired with `CodexState`); the
 * field rides on `Enemy.journalEntry?` which re-exports `CodexEntry`
 * from this module for the per-foe content site (see
 * `src/Enemy/types.ts` for the import + re-export shape).
 */
export interface CodexEntry {
    /** Stable id; consumed by Codex-tab UI as the row key. */
    id: string;
    /** Short label rendered on the unlock toast + Codex row header. */
    title: string;
    /** Long-form chronicle prose for the Codex entry body. */
    body: string;
}

/**
 * Codex slice on `GameState`.
 * Append-only collection of unlocked entry IDs. Each entry id maps
 * back to a `CodexEntry` on the source `Enemy` (or a future
 * dialogue / map-event surface that grants codex entries directly).
 * Consumers (mobile Codex tab, future CLI surface) render entry
 * bodies by looking up the id against the content registry.
 *
 * Wrapper shape (not flat `string[]`) so future per-entry metadata
 * (unlock-timestamp, read-status) can land additive-optionally
 * without breaking the existing surface. Same pattern as `QuestLog`.
 */
export interface CodexState {
    unlockedEntries: string[];
}

export interface GameState {
    version: number;
    /**
     * UUID-shaped identifier for this run. Generated by
     * `generateRunId(() => getRng().random())` at `createNewGameState()`
     * time AND bumped on every `resetRun()` call (the consumer-facing
     * surface for "begin again at the hearth" flows). Persists in save
     * data so future runs-history features can key off per-run identity.
     */
    runId: string;
    player: Character;
    world: WorldState;
    currentEncounter?: Encounter;
    quests: QuestLog;
    flags: string[];
    rngState: number;
    /**
     * Codex slice. Required state slice; defaults to
     * `{ unlockedEntries: [] }` on new games.
     */
    codex: CodexState;
    /**
     * W-01 — cross-act labyrinth (The Aporia) progress: pocket of
     * fragments, opened gates, revealed secrets, the debt ledger, and
     * waystones. Optional lazy slice:
     * absent until the player first enters the continent, so older
     * saves need no migration.
     */
    labyrinth?: LabyrinthProgress;
}
