// axiomancer-mobile/scripts/asset-provenance.test.mjs — the art pipeline's
// two missing gates (phase 71), from `docs/asset-conventions.md`'s own
// "Known gaps" list.
//
//   node --test axiomancer-mobile/scripts/asset-provenance.test.mjs
//
// 1. PROVENANCE COMPLETENESS. The conventions say "No provenance entry, no
//    asset" (§4). Nothing enforced it, and `assets/images/labyrinth/` shipped
//    35 assets with no record at all.
// 2. REGISTRY-VS-DIRECTORY DRIFT. Metro needs static `require()` literals, so
//    a registry and its directory drift in both directions: a require() for a
//    deleted file (a runtime crash) and a file no registry reaches (dead
//    weight in the bundle).
//
// On UNRESOLVED licenses: an asset whose license nobody recorded is NOT the
// same failure as an asset nobody documented. The first is a question only the
// owner can answer; the second is a process gap the loop can close. So a
// missing record FAILS, while an UNRESOLVED license is counted and named on
// every run — visible debt rather than either a permanent red build or a
// silence that lets it be forgotten.

import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import test from 'node:test'
import { fileURLToPath } from 'node:url'

const MOBILE = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const IMAGES = path.join(MOBILE, 'assets', 'images')

const RASTER = new Set(['.png', '.jpg', '.jpeg', '.webp'])

/**
 * Directories that hold no art of their own — platform icon trees generated by
 * Expo's prebuild, not authored assets under the ingest contract.
 */
const NOT_ART_DIRS = new Set(['android', 'ios', 'web'])

/**
 * Directories with one consumed-directly asset and no registry. Recorded so
 * adding a second file has to confront the missing `index.ts` rather than
 * quietly doubling an un-registried directory. `combat` graduated in phase
 * 83 — it now has `index.ts`'s `arenaBackdropFor` resolver.
 */
const REGISTRY_LESS = new Set()

/** Every directory under assets/images that holds raster art. */
function artDirectories(dir = IMAGES, rel = '') {
  const out = []
  const entries = fs.readdirSync(dir, { withFileTypes: true })
  const images = entries.filter((e) => e.isFile() && RASTER.has(path.extname(e.name).toLowerCase()))
  if (images.length > 0 && rel !== '') out.push({ rel, dir, images: images.map((e) => e.name) })
  for (const e of entries) {
    if (!e.isDirectory() || NOT_ART_DIRS.has(e.name)) continue
    out.push(...artDirectories(path.join(dir, e.name), rel ? `${rel}/${e.name}` : e.name))
  }
  return out
}

/** Provenance covering a directory: its own file, or a per-asset sibling. */
function provenanceFor({ dir, images }) {
  const own = path.join(dir, 'provenance.json')
  if (fs.existsSync(own)) return JSON.parse(fs.readFileSync(own, 'utf-8'))
  // The per-file form (`arena-ruined-city.provenance.json`) is equally valid.
  const perAsset = images
    .map((img) => path.join(dir, `${path.basename(img, path.extname(img))}.provenance.json`))
    .filter((p) => fs.existsSync(p))
  return perAsset.length ? perAsset.map((p) => JSON.parse(fs.readFileSync(p, 'utf-8'))) : null
}

const asList = (record) => (Array.isArray(record) ? record : [record])

const dirs = artDirectories()

test('the sweep found art directories to check', () => {
  // Without this every assertion below passes vacuously the moment the layout
  // moves or the extension list drifts.
  assert.ok(dirs.length >= 5, `only found ${dirs.length} art directories`)
  assert.ok(dirs.some((d) => d.rel === 'labyrinth/doors'))
})

test('every art directory has a provenance record', () => {
  const undocumented = dirs.filter((d) => provenanceFor(d) == null).map((d) => d.rel)
  assert.deepEqual(undocumented, [], 'no provenance entry, no asset (asset-conventions.md §4)')
})

test('every provenance record carries date, tool, license and covers', () => {
  const incomplete = []
  for (const d of dirs) {
    for (const entry of asList(provenanceFor(d))) {
      const missing = ['date', 'tool', 'license', 'covers'].filter((k) => entry[k] == null)
      if (missing.length) incomplete.push(`${d.rel}: missing ${missing.join(', ')}`)
    }
  }
  assert.deepEqual(incomplete, [])
})

test('an UNRESOLVED license explains itself and is reported, not hidden', () => {
  const unresolved = []
  for (const d of dirs) {
    for (const entry of asList(provenanceFor(d))) {
      if (String(entry.license).toUpperCase() !== 'UNRESOLVED') continue
      assert.ok(
        entry.license_note && entry.license_note.length > 40,
        `${d.rel}: UNRESOLVED license with no note explaining what is blocked`,
      )
      unresolved.push(`${d.rel} (${Array.isArray(entry.covers) ? entry.covers.length : 1} asset(s))`)
    }
  }
  // Printed on every run. This is DEBT, deliberately not a failure: only the
  // owner can answer the licensing question, and a red build would neither
  // answer it nor let anything else ship.
  if (unresolved.length) {
    console.log(`  asset licensing UNRESOLVED in: ${unresolved.join(', ')}`)
  }
})

// PHASE 103 — this gate had a hole, and a retirement fell through it.
//
// It used to match only `require('./…')`. But `screens/index.ts` reaches ACROSS
// directories by design — its whole header note is that plates are reused from
// `maps/` rather than re-acquired — so every one of its requires is `../…` and
// none of them was ever checked. When `arena-ruined-city.jpg` was retired, the
// registry kept a live `require('../combat/arena-ruined-city.jpg')` and this
// suite stayed green. That is exactly the failure the file's own header calls
// out: "a require() for a deleted file (a runtime crash)".
//
// So registries are now swept for EVERY relative require, and the sweep walks
// every `index.ts` under assets/images rather than only the categories that
// happen to hold raster files of their own — `screens/` holds none, which is
// the second reason it was invisible here.

/** Every `index.ts` under assets/images, registry or not. */
function registryFiles(dir = IMAGES, rel = '') {
  const out = []
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const childRel = rel ? `${rel}/${e.name}` : e.name
    if (e.isDirectory()) {
      if (NOT_ART_DIRS.has(e.name)) continue
      out.push(...registryFiles(path.join(dir, e.name), childRel))
    } else if (e.name === 'index.ts') {
      out.push({ rel: rel || '.', file: path.join(dir, e.name) })
    }
  }
  return out
}

const registries = registryFiles()

test('the sweep found registries to check', () => {
  // Same reason as the directory guard above: without this, a layout move makes
  // the require() gate below pass vacuously.
  assert.ok(registries.length >= 3, `only found ${registries.length} registries`)
  assert.ok(registries.some((r) => r.rel === 'screens'), 'screens/index.ts must be swept')
  assert.ok(registries.some((r) => r.rel === 'combat'))
})

test('every registry require() points at a file that exists', () => {
  const broken = []
  for (const { rel, file } of registries) {
    const source = fs.readFileSync(file, 'utf-8')
    // Relative requires only — `..` included. A bare package specifier is not
    // this gate's business.
    for (const m of source.matchAll(/require\('(\.[^']*)'\)/g)) {
      const target = path.resolve(path.dirname(file), m[1])
      if (!fs.existsSync(target)) broken.push(`${rel}: ${m[1]}`)
    }
  }
  assert.deepEqual(broken, [], 'a require() for a missing file crashes the bundler')
})

// PHASE 103 — the mirror hole. A record whose `covers` names a file that was
// deleted is a provenance entry for nothing: it keeps claiming a licence for an
// asset that no longer ships, and (when the retired asset was the directory's
// only UNRESOLVED one) it keeps printing debt that has already been paid off.
// Nothing checked it, so the retired plate's record survived its own file.
test('every provenance record covers files that actually exist', () => {
  const phantom = []
  for (const d of dirs) {
    for (const entry of asList(provenanceFor(d))) {
      // `covers` is also allowed to be a prose blanket ("every .webp in this
      // directory"). That form names no file, so there is nothing to check.
      if (!Array.isArray(entry.covers)) continue
      for (const claim of entry.covers) {
        // Entries may carry a parenthetical source note, e.g.
        // `"the-stamper.webp (delapouite/stamper.svg)"` — the filename is the
        // first token and the note describes where the art came from.
        const name = String(claim).split(/\s+/)[0]
        if (!fs.existsSync(path.join(d.dir, name))) phantom.push(`${d.rel}: ${name}`)
      }
    }
  }
  assert.deepEqual(phantom, [], 'a record for a deleted asset outlives the asset it documents')
})

test('every art file is reachable from a registry', () => {
  const orphans = []
  for (const { rel, images } of dirs) {
    const category = rel.split('/')[0]
    if (REGISTRY_LESS.has(category)) continue
    const indexPath = path.join(IMAGES, category, 'index.ts')
    if (!fs.existsSync(indexPath)) { orphans.push(`${rel}: no index.ts`); continue }
    const source = fs.readFileSync(indexPath, 'utf-8')
    for (const img of images) {
      if (!source.includes(img)) orphans.push(`${rel}/${img}`)
    }
  }
  assert.deepEqual(orphans, [], 'art in the tree that no registry reaches is dead bundle weight')
})

test('the registry-less list holds only directories that are still registry-less', () => {
  for (const category of REGISTRY_LESS) {
    assert.ok(
      !fs.existsSync(path.join(IMAGES, category, 'index.ts')),
      `${category} has an index.ts now — drop it from REGISTRY_LESS`,
    )
  }
})
