// axiomancer-mobile/scripts/asset-provenance.test.mjs — the art pipeline's
// two missing gates (phase 71), from `docs/asset-conventions.md`'s own
// "Known gaps" list.
//
//   node --test axiomancer-mobile/scripts/asset-provenance.test.mjs
//
// 1. PROVENANCE COMPLETENESS. The conventions say "No provenance entry, no
//    asset" (§4). Nothing enforced it, and `assets/images/labyrinth/` shipped
//    35 assets with no record at all.
// 2. REGISTRY-VS-DIRECTORY DRIFT. Metro needs static `require()` literals, so
//    a registry and its directory drift in both directions: a require() for a
//    deleted file (a runtime crash) and a file no registry reaches (dead
//    weight in the bundle).
//
// On UNRESOLVED licenses: an asset whose license nobody recorded is NOT the
// same failure as an asset nobody documented. The first is a question only the
// owner can answer; the second is a process gap the loop can close. So a
// missing record FAILS, while an UNRESOLVED license is counted and named on
// every run — visible debt rather than either a permanent red build or a
// silence that lets it be forgotten.

import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import test from 'node:test'
import { fileURLToPath } from 'node:url'

const MOBILE = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const IMAGES = path.join(MOBILE, 'assets', 'images')

const RASTER = new Set(['.png', '.jpg', '.jpeg', '.webp'])

/**
 * Directories that hold no art of their own — platform icon trees generated by
 * Expo's prebuild, not authored assets under the ingest contract.
 */
const NOT_ART_DIRS = new Set(['android', 'ios', 'web'])

/**
 * Directories with one consumed-directly asset and no registry. Recorded so
 * adding a second file has to confront the missing `index.ts` rather than
 * quietly doubling an un-registried directory. `combat` graduated in phase
 * 83 — it now has `index.ts`'s `arenaBackdropFor` resolver.
 */
const REGISTRY_LESS = new Set()

/** Every directory under assets/images that holds raster art. */
function artDirectories(dir = IMAGES, rel = '') {
  const out = []
  const entries = fs.readdirSync(dir, { withFileTypes: true })
  const images = entries.filter((e) => e.isFile() && RASTER.has(path.extname(e.name).toLowerCase()))
  if (images.length > 0 && rel !== '') out.push({ rel, dir, images: images.map((e) => e.name) })
  for (const e of entries) {
    if (!e.isDirectory() || NOT_ART_DIRS.has(e.name)) continue
    out.push(...artDirectories(path.join(dir, e.name), rel ? `${rel}/${e.name}` : e.name))
  }
  return out
}

/** Provenance covering a directory: its own file, or a per-asset sibling. */
function provenanceFor({ dir, images }) {
  const own = path.join(dir, 'provenance.json')
  if (fs.existsSync(own)) return JSON.parse(fs.readFileSync(own, 'utf-8'))
  // The per-file form (`arena-ruined-city.provenance.json`) is equally valid.
  const perAsset = images
    .map((img) => path.join(dir, `${path.basename(img, path.extname(img))}.provenance.json`))
    .filter((p) => fs.existsSync(p))
  return perAsset.length ? perAsset.map((p) => JSON.parse(fs.readFileSync(p, 'utf-8'))) : null
}

const asList = (record) => (Array.isArray(record) ? record : [record])

const dirs = artDirectories()

test('the sweep found art directories to check', () => {
  // Without this every assertion below passes vacuously the moment the layout
  // moves or the extension list drifts.
  assert.ok(dirs.length >= 5, `only found ${dirs.length} art directories`)
  assert.ok(dirs.some((d) => d.rel === 'labyrinth/doors'))
})

test('every art directory has a provenance record', () => {
  const undocumented = dirs.filter((d) => provenanceFor(d) == null).map((d) => d.rel)
  assert.deepEqual(undocumented, [], 'no provenance entry, no asset (asset-conventions.md §4)')
})

test('every provenance record carries date, tool, license and covers', () => {
  const incomplete = []
  for (const d of dirs) {
    for (const entry of asList(provenanceFor(d))) {
      const missing = ['date', 'tool', 'license', 'covers'].filter((k) => entry[k] == null)
      if (missing.length) incomplete.push(`${d.rel}: missing ${missing.join(', ')}`)
    }
  }
  assert.deepEqual(incomplete, [])
})

test('an UNRESOLVED license explains itself and is reported, not hidden', () => {
  const unresolved = []
  for (const d of dirs) {
    for (const entry of asList(provenanceFor(d))) {
      if (String(entry.license).toUpperCase() !== 'UNRESOLVED') continue
      assert.ok(
        entry.license_note && entry.license_note.length > 40,
        `${d.rel}: UNRESOLVED license with no note explaining what is blocked`,
      )
      unresolved.push(`${d.rel} (${Array.isArray(entry.covers) ? entry.covers.length : 1} asset(s))`)
    }
  }
  // Printed on every run. This is DEBT, deliberately not a failure: only the
  // owner can answer the licensing question, and a red build would neither
  // answer it nor let anything else ship.
  if (unresolved.length) {
    console.log(`  asset licensing UNRESOLVED in: ${unresolved.join(', ')}`)
  }
})

test('every registry require() points at a file that exists', () => {
  const broken = []
  for (const { rel, dir } of dirs) {
    // Registries live at the category root, not in every subdirectory.
    const indexPath = path.join(IMAGES, rel.split('/')[0], 'index.ts')
    if (!fs.existsSync(indexPath)) continue
    const source = fs.readFileSync(indexPath, 'utf-8')
    for (const m of source.matchAll(/require\('(\.\/[^']+)'\)/g)) {
      const target = path.resolve(path.dirname(indexPath), m[1])
      if (!fs.existsSync(target)) broken.push(`${rel}: ${m[1]}`)
    }
  }
  assert.deepEqual(broken, [], 'a require() for a missing file crashes the bundler')
})

test('every art file is reachable from a registry', () => {
  const orphans = []
  for (const { rel, images } of dirs) {
    const category = rel.split('/')[0]
    if (REGISTRY_LESS.has(category)) continue
    const indexPath = path.join(IMAGES, category, 'index.ts')
    if (!fs.existsSync(indexPath)) { orphans.push(`${rel}: no index.ts`); continue }
    const source = fs.readFileSync(indexPath, 'utf-8')
    for (const img of images) {
      if (!source.includes(img)) orphans.push(`${rel}/${img}`)
    }
  }
  assert.deepEqual(orphans, [], 'art in the tree that no registry reaches is dead bundle weight')
})

test('the registry-less list holds only directories that are still registry-less', () => {
  for (const category of REGISTRY_LESS) {
    assert.ok(
      !fs.existsSync(path.join(IMAGES, category, 'index.ts')),
      `${category} has an index.ts now — drop it from REGISTRY_LESS`,
    )
  }
})
