#!/usr/bin/env node
// Build the DevLog catalog as one self-contained HTML document:
//   - devlog/catalog.html   cards + enemies + effects, with inline CSS/JS
//
// The JSON is produced by `npm run catalog:export` (ts-node, reads the mechanics
// libraries + mobile art registries). This renderer is zero-dependency and only
// reads the committed JSON + copied art, so it can run on any host.
//
// Usage: node scripts/build-catalog.mjs   (or: npm run catalog:build)

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { escapeHtml, inline, page } from "./devlog-shell.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const DEVLOG = join(ROOT, "devlog");
const DATA = join(DEVLOG, "data");

const BACK = { href: "./index.html", label: "← Axiomancer" };
const FOOTER = "single-file catalog generated by <code>scripts/build-catalog.mjs</code>";

function load(name) {
  const path = join(DATA, `${name}.json`);
  if (!existsSync(path)) {
    console.warn(`catalog: missing ${name}.json — run "npm run catalog:export" first.`);
    return [];
  }
  return JSON.parse(readFileSync(path, "utf8"));
}

const CATALOG_EXTRA_STYLE = `
.catalog-nav {
  position: sticky; top: 52px; z-index: 4; display: flex; flex-wrap: wrap; gap: 8px;
  margin: -4px 0 22px; padding: 10px 0; background: var(--bg); border-bottom: 1px solid var(--border);
}
.catalog-nav a {
  display: inline-block; padding: 6px 10px; border: 1px solid var(--border); border-radius: 999px;
  background: var(--card); color: var(--fg); text-decoration: none; font-size: 13px; font-weight: 700;
}
.catalog-nav a:hover { background: var(--row); }
.catalog-section { margin: 34px 0 52px; scroll-margin-top: 110px; }
.catalog-section > h2 { font-size: 24px; margin: 0 0 6px; }
.catalog-section .intro { color: var(--muted); margin: 0 0 14px; }

/* ── Card FACE — the #5 SIDE RAIL design (die/stance-coloured spine) ──────── */
.gcard { position: relative; }
.cface {
  position: relative; aspect-ratio: 5 / 7; overflow: hidden; background: #0c0a08;
  font-family: "IM Fell English", Georgia, "Times New Roman", serif;
}
.cface .cart { position: absolute; inset: 0; }
.cface .cart img { width: 100%; height: 100%; object-fit: cover; object-position: top center; display: block; }
.cface .cart.none { display: flex; align-items: center; justify-content: center; color: rgba(232,223,200,.35); font-size: 44px; }
.cface .ctint { position: absolute; inset: 0; background: var(--rc); mix-blend-mode: soft-light; opacity: .17; }
.cface .cscrim {
  position: absolute; left: 0; right: 0; bottom: 0; height: 80%; pointer-events: none;
  background: linear-gradient(to top, #06050a 20%, color-mix(in srgb, #06050a 82%, var(--rc)) 46%, rgba(6,5,4,.5) 66%, transparent);
}
.cface .crail {
  position: absolute; left: 0; top: 0; bottom: 0; width: 26px; z-index: 2;
  background: linear-gradient(var(--rc), color-mix(in srgb, var(--rc) 45%, #000));
  border-right: 1px solid rgba(0,0,0,.5);
  display: flex; flex-direction: column; align-items: center; justify-content: flex-end; padding-bottom: 11px;
}
.cface .crail .cvert {
  writing-mode: vertical-rl; transform: rotate(180deg);
  font-family: "Bebas Neue", "Arial Narrow", system-ui, sans-serif;
  font-size: 11px; letter-spacing: 2px; color: rgba(255,255,255,.9); white-space: nowrap;
}
/* ① the GIANT free-effect glyph with its intensity centred INSIDE it. */
.cface .cfree {
  position: absolute; left: 4px; top: 4px; z-index: 3; width: 46px; height: 46px;
  display: flex; align-items: center; justify-content: center;
  font-size: 42px; line-height: 1; color: var(--rc); text-shadow: 0 2px 5px rgba(0,0,0,.85);
  background: radial-gradient(circle at 48% 46%, rgba(6,5,10,.82) 40%, rgba(6,5,10,0) 72%);
}
.cface .cfree .cfreeval {
  position: absolute; inset: 0; display: flex; align-items: center; justify-content: center;
  font-size: 15px; font-weight: 600; color: #fff;
  font-family: "JetBrains Mono", ui-monospace, monospace; text-shadow: 0 1px 3px rgba(0,0,0,.95);
}
.cface .crarity {
  position: absolute; top: 7px; right: 7px; z-index: 2; background: rgba(8,7,6,.7);
  font-family: "Bebas Neue", "Arial Narrow", system-ui, sans-serif;
  font-size: 10px; letter-spacing: 1px; padding: 1px 6px; border: 1px solid;
}
.cface .cbtm { position: absolute; left: 38px; right: 12px; bottom: 12px; z-index: 2; }
.cface .cbtm .cname {
  font-family: "Pirata One", "IM Fell English", Georgia, serif; font-size: 23px; line-height: 1.02;
  color: #e8dfc8; text-shadow: 0 2px 6px #000;
}
.cface .cbtm .crule { height: 1px; background: rgba(232,223,200,.22); margin: 8px 0; }
.cface .cbtm .cpaid {
  display: flex; gap: 7px; align-items: flex-start;
  font-family: "IM Fell English", Georgia, serif; font-size: 13.5px; line-height: 1.35; color: #e8dfc8;
}
.cface .cbtm .cpaid .ccube { flex-shrink: 0; margin-top: 2px; }
.cface .cbtm .cpaid b {
  font-family: "Bebas Neue", "Arial Narrow", system-ui, sans-serif; font-weight: 700;
  letter-spacing: .5px; text-transform: uppercase; color: var(--rc);
}
`;

// Stance → rail colour (mirrors the app's DIE palette) and rarity frame.
const STANCE_COLOR = { body: "#d6543f", mind: "#4f7fd6", heart: "#9a5fd0", wild: "#d9b44a" };
const RARITY_META = {
  common: { label: "COMMON", color: "#8a8273", glow: 0 },
  uncommon: { label: "UNCOMMON", color: "#6b8eb0", glow: 0 },
  rare: { label: "RARE", color: "#9a6ad6", glow: 12 },
};
// Keyword vocabulary bolded inside the PAID sentence (the card overlay defines
// them; the face just flags that they ARE keywords). Longest-first so multi-word
// keywords win the match.
const KEYWORD_WORDS = [
  "STRIP BUFF", "HEAL SELF", "DAMAGE", "POISON", "BLEED", "BURN", "MARK", "GUARD",
  "BARRIER", "RIPOSTE", "STUN", "SLOW", "CONFUSION", "SILENCE", "STAGGER", "BACKFIRE",
  "SWAY", "REAP", "SOUL", "SOULS", "FORETELL", "PREMISE", "ECHO", "FORGE", "DRAW",
  "REGEN", "SIPHON", "EXECUTE", "RUPTURE", "COMPOUND", "ENCHANT", "DISENCHANT",
  "PROLONG", "RECALL", "PERORATION", "CONCEDE", "CAPITULATE", "VULNERABLE", "THORNS",
  "TICK", "DOT", "CLEANSE", "PERORATE", "REPRISE", "PIP", "PIPS",
].sort((a, b) => b.length - a.length);

function boldKeywords(text) {
  if (!text) return "";
  const esc = KEYWORD_WORDS.map((w) => w.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"));
  const re = new RegExp(`\\b(${esc.join("|")})\\b`, "gi");
  // Split into keyword / non-keyword runs and escape each part before joining.
  const out = [];
  let last = 0;
  let m;
  while ((m = re.exec(text)) !== null) {
    if (m.index > last) out.push(escapeHtml(text.slice(last, m.index)));
    out.push(`<b>${escapeHtml(m[0])}</b>`);
    last = m.index + m[0].length;
  }
  if (last < text.length) out.push(escapeHtml(text.slice(last)));
  return out.join("");
}

function chipVal(chips, key) {
  const c = (chips || []).find((x) => x.k === key);
  return c ? c.v : "";
}

// A tiny isometric die (matches the app's stance cube) tinted the rail colour.
function cubeSvg(color) {
  return (
    `<svg class="ccube" viewBox="0 0 24 24" width="18" height="18" aria-hidden="true">` +
    `<path d="M12 3 L21 8 L12 13 L3 8Z" fill="${color}"/>` +
    `<path d="M3 8 L12 13 L12 21 L3 16Z" fill="color-mix(in srgb, ${color} 68%, #000)"/>` +
    `<path d="M21 8 L12 13 L12 21 L21 16Z" fill="color-mix(in srgb, ${color} 42%, #000)"/>` +
    `</svg>`
  );
}

// The #5 rail card FACE — ① giant FREE glyph + intensity, ② PAID sentence
// (keywords bolded), stance rail + vertical type label, name, rarity tag.
function cardFaceHtml(c) {
  const stance = (chipVal(c.chips, "Stance") || "body").toLowerCase();
  const rc = STANCE_COLOR[stance] || "#8a8273";
  const kind = (chipVal(c.chips, "Kind") || "spell").toLowerCase();
  const kindLabel = kind === "disenchant" ? "CURSE" : kind.toUpperCase();
  const typeLabel = `${stance.toUpperCase()} · ${kindLabel}`;
  const rarKey = (chipVal(c.chips, "Rank").match(/\((\w+)\)/)?.[1] || "common").toLowerCase();
  const rar = RARITY_META[rarKey] || RARITY_META.common;
  const face = c.face || {};

  const art = c.image
    ? `<div class="cart"><img loading="lazy" src="${escapeHtml(c.image)}" alt="${escapeHtml(c.name)}"></div>`
    : `<div class="cart none" role="img" aria-label="${escapeHtml(c.name)} (no art)">🂠</div>`;
  const fv = face.freeVal;
  const fvText = fv ? (/^\d+$/.test(fv) ? "+" + fv : fv) : "";
  const freeGlyph = face.freeGlyph
    ? `<div class="cfree">${escapeHtml(face.freeGlyph)}` +
      (fvText ? `<span class="cfreeval">${escapeHtml(fvText)}</span>` : "") +
      `</div>`
    : "";
  const paidLine = face.paid
    ? `<div class="cpaid">${cubeSvg(rc)}<span>${boldKeywords(face.paid)}</span></div>`
    : "";

  return (
    `<div class="cface" style="--rc:${rc}">` +
    art +
    `<div class="ctint"></div><div class="cscrim"></div>` +
    `<div class="crail"><div class="cvert">${escapeHtml(typeLabel)}</div></div>` +
    freeGlyph +
    `<div class="crarity" style="color:${rar.color};border-color:${rar.color}88">${rar.label}</div>` +
    `<div class="cbtm"><div class="cname">${inline(c.name)}</div>` +
    `<div class="crule"></div>${paidLine}</div>` +
    `</div>`
  );
}

// A live client-side filter box shared by the cards/enemies sections. It is
// scoped by data-target so the single catalog page never reuses duplicate IDs.
const CATALOG_JS = `
<script>
(function () {
  function wireFilter(input) {
    var targetId = input.getAttribute('data-target');
    var grid = targetId ? document.getElementById(targetId) : null;
    var note = input.parentNode ? input.parentNode.querySelector('.count-note') : null;
    if (!grid) return;
    var items = Array.prototype.slice.call(grid.children);
    var total = items.length;
    input.addEventListener('input', function () {
      var q = input.value.trim().toLowerCase();
      var shown = 0;
      items.forEach(function (el) {
        var hit = !q || (el.getAttribute('data-search') || '').indexOf(q) !== -1;
        el.style.display = hit ? '' : 'none';
        if (hit) shown++;
      });
      if (note) note.textContent = q ? shown + ' of ' + total + ' shown' : total + ' total';
    });
  }
  Array.prototype.forEach.call(document.querySelectorAll('.catalog-filter'), wireFilter);
})();
</script>`;

function searchbar(targetId, placeholder, total, noun) {
  return (
    `<div class="searchbar"><input class="catalog-filter" data-target="${escapeHtml(targetId)}" type="search" autocomplete="off" ` +
    `placeholder="${escapeHtml(placeholder)}"><p class="count-note">${total} ${noun}</p></div>`
  );
}

function artOrPlaceholder(image, cls, glyph, alt) {
  if (image) {
    return `<div class="${cls}"><img loading="lazy" src="${escapeHtml(image)}" alt="${escapeHtml(alt)}"></div>`;
  }
  return `<div class="${cls} none" role="img" aria-label="${escapeHtml(alt)} (no art)">${glyph}</div>`;
}

// Raw-stat rendering — compact key/value badges + spelled-out mechanic lines.
function chipsHtml(chips) {
  if (!chips || !chips.length) return "";
  return (
    `<div class="statrow">` +
    chips
      .map((c) => `<span class="stat"><span class="k">${escapeHtml(c.k)}</span>${escapeHtml(c.v)}</span>`)
      .join("") +
    `</div>`
  );
}
function linesHtml(lines) {
  if (!lines || !lines.length) return "";
  return `<ul class="mods">` + lines.map((l) => `<li>${escapeHtml(l)}</li>`).join("") + `</ul>`;
}
function searchText(name, chips, lines) {
  const parts = [name]
    .concat((chips || []).map((c) => `${c.k} ${c.v}`))
    .concat(lines || []);
  return escapeHtml(parts.join(" ").toLowerCase());
}

// ---------------------------------------------------------------------------
// Cards — name · image · card text
// ---------------------------------------------------------------------------
function renderCards(cards) {
  const grid = cards
    .map((c) => {
      const search = searchText(c.name, c.chips, c.lines);
      const rarKey = (chipVal(c.chips, "Rank").match(/\((\w+)\)/)?.[1] || "common").toLowerCase();
      const rar = RARITY_META[rarKey] || RARITY_META.common;
      const frame =
        `border-color:${rar.color}` +
        (rar.glow ? `;box-shadow:0 0 ${rar.glow}px ${rar.color}55` : "");
      return (
        `  <article class="gcard" style="${frame}" data-search="${search}">` +
        cardFaceHtml(c) +
        `<div class="body">` +
        chipsHtml(c.chips) +
        linesHtml(c.lines) +
        `</div></article>`
      );
    })
    .join("\n");

  return (
    `<section id="cards" class="catalog-section">\n` +
    `<h2>Cards</h2>\n` +
    `<p class="intro">Name, art, stance, tier, target, rank, learn level, and rules text.</p>\n` +
    searchbar("cards-grid", "Filter cards by name or text…", cards.length, "cards") +
    `\n<div class="grid-cards" id="cards-grid">\n${grid}\n</div>\n` +
    `</section>`
  );
}

// ---------------------------------------------------------------------------
// Enemies — image · name · stats · attacks (skills + how it fights)
// ---------------------------------------------------------------------------
function renderEnemies(enemies) {
  const grid = enemies
    .map((e) => {
      const search = escapeHtml((e.name + " " + (e.difficulty || "") + " " + (e.logic || "")).toLowerCase());
      const portrait = artOrPlaceholder(e.image, "portrait", "☠", e.name);

      const stats =
        `<div class="statrow">` +
        `<span class="stat hp"><span class="k">HP</span>${e.maxHealth}</span>` +
        `<span class="stat body"><span class="k">Body</span>${e.stats.body}</span>` +
        `<span class="stat mind"><span class="k">Mind</span>${e.stats.mind}</span>` +
        `<span class="stat heart"><span class="k">Heart</span>${e.stats.heart}</span>` +
        `</div>`;

      const skills = (e.cards || []).length
        ? e.cards
            .map(
              (s) =>
                `<div class="skill"><div class="sk-name">${inline(s.name)}</div>` +
                `<div class="sk-text">${inline(s.text || "")}</div></div>`
            )
            .join("")
        : `<p class="no-skills">No signature skills — fights with basic stance moves.</p>`;

      const hint = e.stanceHint ? `<p class="hint">“${inline(e.stanceHint)}”</p>` : "";

      return (
        `  <article class="ecard" data-search="${search}">${portrait}` +
        `<div class="body">` +
        `<h2 class="name">${inline(e.name)}</h2>` +
        `<p class="sub">Level ${e.level} · ${escapeHtml(e.difficulty || "")}</p>` +
        stats +
        `<div class="sec-label">Attacks</div>` +
        `<p class="fights">${inline(e.logicBlurb || e.logic || "")}</p>` +
        hint +
        skills +
        `</div></article>`
      );
    })
    .join("\n");

  return (
    `<section id="enemies" class="catalog-section">\n` +
    `<h2>Enemies</h2>\n` +
    `<p class="intro">Portraits, level, difficulty, stats, behavior doctrine, and signature skills.</p>\n` +
    searchbar("enemies-grid", "Filter enemies by name, difficulty, behaviour…", enemies.length, "foes") +
    `\n<div class="grid-enemies" id="enemies-grid">\n${grid}\n</div>\n` +
    `</section>`
  );
}

// ---------------------------------------------------------------------------
// Effects — name · glyph · what it does (grouped buffs / debuffs)
// ---------------------------------------------------------------------------
function renderEffects(effects) {
  const row = (e) =>
    `  <div class="eff"><div class="glyph" style="--gc:${escapeHtml(e.color)}" role="img" ` +
    `aria-label="${escapeHtml(e.name)} glyph">${escapeHtml(e.glyph)}</div>` +
    `<div><div class="name">${inline(e.name)}</div>` +
    chipsHtml(e.chips) +
    linesHtml(e.lines) +
    `</div></div>`;

  const section = (label, list) =>
    list.length
      ? `<div class="sec-label">${label} · ${list.length}</div>\n<div class="eff-list">\n${list
          .map(row)
          .join("\n")}\n</div>`
      : "";

  const buffs = effects.filter((e) => e.type === "buff");
  const debuffs = effects.filter((e) => e.type === "debuff");

  return (
    `<section id="effects" class="catalog-section">\n` +
    `<h2>Effects</h2>\n` +
    `<p class="intro">${effects.length} status effects — the glyph is how each one reads on the combat board.</p>\n` +
    section("Buffs", buffs) +
    "\n" +
    section("Debuffs", debuffs) +
    `\n</section>`
  );
}

function buildCatalog() {
  const cards = load("cards");
  const enemies = load("enemies");
  const effects = load("effects");

  const body =
    `<h1>Catalog</h1>\n` +
    `<p class="muted">A single HTML document containing cards, enemies, effects, inline CSS, and inline JavaScript.</p>\n` +
    `<nav class="catalog-nav" aria-label="Catalog sections">` +
    `<a href="#cards">Cards (${cards.length})</a>` +
    `<a href="#enemies">Enemies (${enemies.length})</a>` +
    `<a href="#effects">Effects (${effects.length})</a>` +
    `</nav>\n` +
    renderCards(cards) +
    "\n" +
    renderEnemies(enemies) +
    "\n" +
    renderEffects(effects) +
    "\n" +
    CATALOG_JS;

  writeFileSync(
    join(DEVLOG, "catalog.html"),
    page({
      title: "Axiomancer — Catalog",
      home: BACK,
      crumb: "Catalog",
      body,
      extraStyle: CATALOG_EXTRA_STYLE,
      footerNote: FOOTER,
    })
  );

  return { cards: cards.length, enemies: enemies.length, effects: effects.length };
}

const counts = buildCatalog();
console.log(`catalog: built single HTML catalog (${counts.cards} cards, ${counts.enemies} enemies, ${counts.effects} effects)`);
