#!/usr/bin/env node
// Build the DevLog catalog as one self-contained HTML document:
//   - devlog/catalog.html   cards + enemies + effects, with inline CSS/JS
//
// The JSON is produced by `npm run catalog:export` (ts-node, reads the mechanics
// libraries + mobile art registries). This renderer is zero-dependency and only
// reads the committed JSON + copied art, so it can run on any host.
//
// Usage: node scripts/build-catalog.mjs   (or: npm run catalog:build)

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { escapeHtml, inline, page } from "./devlog-shell.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const DEVLOG = join(ROOT, "devlog");
const DATA = join(DEVLOG, "data");

const BACK = { href: "./index.html", label: "← Axiomancer" };
const FOOTER = "single-file catalog generated by <code>scripts/build-catalog.mjs</code>";

function load(name) {
  const path = join(DATA, `${name}.json`);
  if (!existsSync(path)) {
    console.warn(`catalog: missing ${name}.json — run "npm run catalog:export" first.`);
    return [];
  }
  return JSON.parse(readFileSync(path, "utf8"));
}

const CATALOG_EXTRA_STYLE = `
.catalog-nav {
  position: sticky; top: 52px; z-index: 4; display: flex; flex-wrap: wrap; gap: 8px;
  margin: -4px 0 22px; padding: 10px 0; background: var(--bg); border-bottom: 1px solid var(--border);
}
.catalog-nav a {
  display: inline-block; padding: 6px 10px; border: 1px solid var(--border); border-radius: 999px;
  background: var(--card); color: var(--fg); text-decoration: none; font-size: 13px; font-weight: 700;
}
.catalog-nav a:hover { background: var(--row); }
.catalog-section { margin: 34px 0 52px; scroll-margin-top: 110px; }
.catalog-section > h2 { font-size: 24px; margin: 0 0 6px; }
.catalog-section .intro { color: var(--muted); margin: 0 0 14px; }

/* ── Card FACE — a faithful CSS port of the in-combat CombatCardFace (large,
      Option A layout). The stance/keyword/orb hues arrive as inline --vars per
      card; everything else is fixed frame chrome so the catalog reads as the
      game does. ─────────────────────────────────────────────────────────── */
.grid-cards { grid-template-columns: repeat(auto-fill, minmax(13rem, 1fr)); align-items: start; }
.gcard.is-face { background: none; border: 0; border-radius: 0; overflow: visible; }
.cardface {
  position: relative; aspect-ratio: 132 / 194; border-radius: 8px;
  border: 2px solid rgba(0,0,0,0.9); background: #14110e;
  box-shadow: 0 3px 6px rgba(0,0,0,0.5); overflow: hidden;
}
.cardface.inert { filter: saturate(0.72) brightness(0.94); }
.cf-inner {
  position: absolute; inset: 0; border: 1.5px solid var(--border); border-radius: 6px;
  overflow: hidden; display: flex; flex-direction: column; background: #14110e;
}
.cf-art { position: relative; height: 48%; background: #0c0a08; }
.cf-art img { position: absolute; inset: 0; width: 100%; height: 100%; object-fit: cover; display: block; }
.cf-tint { position: absolute; inset: 0; background: var(--stance); opacity: 0.14; }
.cf-tint-low {
  position: absolute; left: 0; right: 0; bottom: 0; height: 55%;
  background: linear-gradient(to bottom, transparent, var(--stance)); opacity: 0.5;
}
.cf-orb {
  position: absolute; z-index: 3; top: 8px; left: 8px; width: 44px; height: 44px;
  border-radius: 50%; background: var(--orb); border: 1.5px solid rgba(0,0,0,0.65);
  box-shadow: 0 2px 3px rgba(0,0,0,0.6); display: flex; align-items: center; justify-content: center;
}
.cf-shine { position: absolute; top: 4px; left: 6px; width: 40%; height: 30%; border-radius: 50%; background: rgba(255,255,255,0.32); }
.cf-glyph { color: #fff; font-size: 22px; line-height: 1; text-shadow: 0 1px 2px rgba(0,0,0,0.8); }
.cf-lower { flex: 1; display: flex; flex-direction: column; min-height: 0; }
.cf-nameband {
  position: relative; background: var(--stance); padding: 4px 6px; text-align: center;
  border-top: 1px solid rgba(255,255,255,0.28); border-bottom: 1px solid rgba(0,0,0,0.45);
}
.cf-nameband::before { content: ""; position: absolute; inset: 0; background: rgba(0,0,0,0.30); }
.cf-name {
  position: relative; font-family: Georgia, "Times New Roman", serif; font-weight: 700;
  font-size: 17px; line-height: 1.15; color: #f3e9d2; letter-spacing: 0.3px;
  text-shadow: 0 1px 3px rgba(0,0,0,0.6);
  /* The game shrinks the name to one line; on the web we let a long name wrap
     rather than clip it — a catalog must never hide a card's name. */
  display: block; text-wrap: balance;
}
.cf-rail { flex: 1; display: flex; align-items: stretch; background: rgba(10,8,6,0.62); min-height: 0; }
.cf-half {
  flex: 1; min-width: 0; display: flex; flex-direction: column; align-items: center;
  justify-content: center; text-align: center; padding: 4px 4px; gap: 2px;
}
.cf-div { width: 1px; background: rgba(255,255,255,0.18); margin: 4px 0; }
.cf-head { font-size: 12px; letter-spacing: 1.2px; font-weight: 700; line-height: 1.1; }
.cf-free-head { color: #9c937f; }
.cf-paid-head { color: var(--kw); }
.cf-val {
  font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
  font-size: 15px; line-height: 1.2;
}
.cf-free-val { color: #f1e7d0; }
.cf-paid-val { color: var(--kw); }
.cf-dieline {
  align-self: center; margin: 0 0 3px; padding: 0 5px;
  font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
  font-size: 9px; line-height: 1.3; color: #d4c026; letter-spacing: 0.2px; text-align: center;
}
.cf-typestrip {
  border-top: 1px solid rgba(255,255,255,0.12); background: rgba(0,0,0,0.55);
  text-align: center; padding: 3px 2px; font-size: 9px; letter-spacing: 1.6px; color: #9c937f;
}
`;

// A live client-side filter box shared by the cards/enemies sections. It is
// scoped by data-target so the single catalog page never reuses duplicate IDs.
const CATALOG_JS = `
<script>
(function () {
  function wireFilter(input) {
    var targetId = input.getAttribute('data-target');
    var grid = targetId ? document.getElementById(targetId) : null;
    var note = input.parentNode ? input.parentNode.querySelector('.count-note') : null;
    if (!grid) return;
    var items = Array.prototype.slice.call(grid.children);
    var total = items.length;
    input.addEventListener('input', function () {
      var q = input.value.trim().toLowerCase();
      var shown = 0;
      items.forEach(function (el) {
        var hit = !q || (el.getAttribute('data-search') || '').indexOf(q) !== -1;
        el.style.display = hit ? '' : 'none';
        if (hit) shown++;
      });
      if (note) note.textContent = q ? shown + ' of ' + total + ' shown' : total + ' total';
    });
  }
  Array.prototype.forEach.call(document.querySelectorAll('.catalog-filter'), wireFilter);
})();
</script>`;

function searchbar(targetId, placeholder, total, noun) {
  return (
    `<div class="searchbar"><input class="catalog-filter" data-target="${escapeHtml(targetId)}" type="search" autocomplete="off" ` +
    `placeholder="${escapeHtml(placeholder)}"><p class="count-note">${total} ${noun}</p></div>`
  );
}

function artOrPlaceholder(image, cls, glyph, alt) {
  if (image) {
    return `<div class="${cls}"><img loading="lazy" src="${escapeHtml(image)}" alt="${escapeHtml(alt)}"></div>`;
  }
  return `<div class="${cls} none" role="img" aria-label="${escapeHtml(alt)} (no art)">${glyph}</div>`;
}

// Raw-stat rendering — compact key/value badges + spelled-out mechanic lines.
function chipsHtml(chips) {
  if (!chips || !chips.length) return "";
  return (
    `<div class="statrow">` +
    chips
      .map((c) => `<span class="stat"><span class="k">${escapeHtml(c.k)}</span>${escapeHtml(c.v)}</span>`)
      .join("") +
    `</div>`
  );
}
function linesHtml(lines) {
  if (!lines || !lines.length) return "";
  return `<ul class="mods">` + lines.map((l) => `<li>${escapeHtml(l)}</li>`).join("") + `</ul>`;
}
function searchText(name, chips, lines) {
  const parts = [name]
    .concat((chips || []).map((c) => `${c.k} ${c.v}`))
    .concat(lines || []);
  return escapeHtml(parts.join(" ").toLowerCase());
}

// ---------------------------------------------------------------------------
// Cards — the exact 5-zone combat FACE (art · stance orb · name band · ◇FREE /
// ◆PAID split rail · die line · type strip). The face record is produced by the
// game's own `faceStats` presenter (see scripts/export-catalog.ts) so the
// catalog card can never drift from what the player sees in combat.
// ---------------------------------------------------------------------------
function faceHtml(c) {
  const f = c.face;
  // Back-compat: a JSON without the face falls back to the old art + stats view.
  if (!f) {
    return (
      artOrPlaceholder(c.image, "art", "🂠", c.name) +
      `<div class="body"><div class="name">${inline(c.name)}</div>` +
      chipsHtml(c.chips) +
      linesHtml(c.lines) +
      `</div>`
    );
  }

  const art = c.image
    ? `<img loading="lazy" src="${escapeHtml(c.image)}" alt="${escapeHtml(c.name)}">`
    : "";
  const dieLine = f.dieLine
    ? `<div class="cf-dieline">${escapeHtml(f.dieLine)}</div>`
    : "";
  const vars =
    `--stance:${escapeHtml(f.stanceColor)};--kw:${escapeHtml(f.kwColor)};` +
    `--border:${escapeHtml(f.borderColor)};--orb:${escapeHtml(f.orbColor)}`;

  return (
    `<div class="cardface${f.inert ? " inert" : ""}" style="${vars}">` +
    `<div class="cf-inner">` +
    `<div class="cf-art">${art}<div class="cf-tint"></div><div class="cf-tint-low"></div></div>` +
    `<div class="cf-orb"><span class="cf-shine"></span><span class="cf-glyph">${escapeHtml(f.glyph)}</span></div>` +
    `<div class="cf-lower">` +
    `<div class="cf-nameband"><span class="cf-name">${inline(c.name)}</span></div>` +
    `<div class="cf-rail">` +
    `<div class="cf-half"><div class="cf-head cf-free-head">◇ ${escapeHtml(f.freeKeyword)}</div>` +
    `<div class="cf-val cf-free-val">${escapeHtml(f.freeValue)}</div></div>` +
    `<div class="cf-div"></div>` +
    `<div class="cf-half"><div class="cf-head cf-paid-head">◆ ${escapeHtml(f.paidKeyword)}</div>` +
    `<div class="cf-val cf-paid-val">${escapeHtml(f.paidValue)}</div></div>` +
    `</div>` +
    dieLine +
    `<div class="cf-typestrip">${escapeHtml(f.typeStrip)}</div>` +
    `</div></div></div>`
  );
}

function renderCards(cards) {
  const grid = cards
    .map((c) => {
      const search = searchText(c.name, c.chips, c.lines);
      return `  <article class="gcard is-face" data-search="${search}">${faceHtml(c)}</article>`;
    })
    .join("\n");

  return (
    `<section id="cards" class="catalog-section">\n` +
    `<h2>Cards</h2>\n` +
    `<p class="intro">Every card drawn as its in-combat face — art, stance orb, name band, the ◇ free / ◆ die split, and the type strip.</p>\n` +
    searchbar("cards-grid", "Filter cards by name or text…", cards.length, "cards") +
    `\n<div class="grid-cards" id="cards-grid">\n${grid}\n</div>\n` +
    `</section>`
  );
}

// ---------------------------------------------------------------------------
// Enemies — image · name · stats · attacks (skills + how it fights)
// ---------------------------------------------------------------------------
function renderEnemies(enemies) {
  const grid = enemies
    .map((e) => {
      const search = escapeHtml((e.name + " " + (e.difficulty || "") + " " + (e.logic || "")).toLowerCase());
      const portrait = artOrPlaceholder(e.image, "portrait", "☠", e.name);

      const stats =
        `<div class="statrow">` +
        `<span class="stat hp"><span class="k">HP</span>${e.maxHealth}</span>` +
        `<span class="stat body"><span class="k">Body</span>${e.stats.body}</span>` +
        `<span class="stat mind"><span class="k">Mind</span>${e.stats.mind}</span>` +
        `<span class="stat heart"><span class="k">Heart</span>${e.stats.heart}</span>` +
        `</div>`;

      const skills = (e.cards || []).length
        ? e.cards
            .map(
              (s) =>
                `<div class="skill"><div class="sk-name">${inline(s.name)}</div>` +
                `<div class="sk-text">${inline(s.text || "")}</div></div>`
            )
            .join("")
        : `<p class="no-skills">No signature skills — fights with basic stance moves.</p>`;

      const hint = e.stanceHint ? `<p class="hint">“${inline(e.stanceHint)}”</p>` : "";

      return (
        `  <article class="ecard" data-search="${search}">${portrait}` +
        `<div class="body">` +
        `<h2 class="name">${inline(e.name)}</h2>` +
        `<p class="sub">Level ${e.level} · ${escapeHtml(e.difficulty || "")}</p>` +
        stats +
        `<div class="sec-label">Attacks</div>` +
        `<p class="fights">${inline(e.logicBlurb || e.logic || "")}</p>` +
        hint +
        skills +
        `</div></article>`
      );
    })
    .join("\n");

  return (
    `<section id="enemies" class="catalog-section">\n` +
    `<h2>Enemies</h2>\n` +
    `<p class="intro">Portraits, level, difficulty, stats, behavior doctrine, and signature skills.</p>\n` +
    searchbar("enemies-grid", "Filter enemies by name, difficulty, behaviour…", enemies.length, "foes") +
    `\n<div class="grid-enemies" id="enemies-grid">\n${grid}\n</div>\n` +
    `</section>`
  );
}

// ---------------------------------------------------------------------------
// Effects — name · glyph · what it does (grouped buffs / debuffs)
// ---------------------------------------------------------------------------
function renderEffects(effects) {
  const row = (e) =>
    `  <div class="eff"><div class="glyph" style="--gc:${escapeHtml(e.color)}" role="img" ` +
    `aria-label="${escapeHtml(e.name)} glyph">${escapeHtml(e.glyph)}</div>` +
    `<div><div class="name">${inline(e.name)}</div>` +
    chipsHtml(e.chips) +
    linesHtml(e.lines) +
    `</div></div>`;

  const section = (label, list) =>
    list.length
      ? `<div class="sec-label">${label} · ${list.length}</div>\n<div class="eff-list">\n${list
          .map(row)
          .join("\n")}\n</div>`
      : "";

  const buffs = effects.filter((e) => e.type === "buff");
  const debuffs = effects.filter((e) => e.type === "debuff");

  return (
    `<section id="effects" class="catalog-section">\n` +
    `<h2>Effects</h2>\n` +
    `<p class="intro">${effects.length} status effects — the glyph is how each one reads on the combat board.</p>\n` +
    section("Buffs", buffs) +
    "\n" +
    section("Debuffs", debuffs) +
    `\n</section>`
  );
}

function buildCatalog() {
  const cards = load("cards");
  const enemies = load("enemies");
  const effects = load("effects");

  const body =
    `<h1>Catalog</h1>\n` +
    `<p class="muted">A single HTML document containing cards, enemies, effects, inline CSS, and inline JavaScript.</p>\n` +
    `<nav class="catalog-nav" aria-label="Catalog sections">` +
    `<a href="#cards">Cards (${cards.length})</a>` +
    `<a href="#enemies">Enemies (${enemies.length})</a>` +
    `<a href="#effects">Effects (${effects.length})</a>` +
    `</nav>\n` +
    renderCards(cards) +
    "\n" +
    renderEnemies(enemies) +
    "\n" +
    renderEffects(effects) +
    "\n" +
    CATALOG_JS;

  writeFileSync(
    join(DEVLOG, "catalog.html"),
    page({
      title: "Axiomancer — Catalog",
      home: BACK,
      crumb: "Catalog",
      body,
      extraStyle: CATALOG_EXTRA_STYLE,
      footerNote: FOOTER,
    })
  );

  return { cards: cards.length, enemies: enemies.length, effects: effects.length };
}

const counts = buildCatalog();
console.log(`catalog: built single HTML catalog (${counts.cards} cards, ${counts.enemies} enemies, ${counts.effects} effects)`);
